### ISSUE TITLE
Support the Icon tab

### ISSUE THREAD

**Issue by ogaclejapan** [ogaclejapan/SmartTabLayout#1]

**Comment by jjhesk** [comment]
lets support generic textview that people can using their own text view extended from textview inside the tab.

**Comment by jjhesk** [comment]
that would be awesome to add frame around each tab.

**Comment by ogaclejapan** [comment]
Hi, @jjhesk 

I tried to implement.
What do you think about the implementation?

**Comment by ogaclejapan** [comment]
Merged.
