### ISSUE TITLE
Can we load strip icons via URL?

### ISSUE THREAD

**Issue by ashishjain002** [ogaclejapan/SmartTabLayout#101]
Can we load strip icons via URL? 
like if i want to use dynamic icons.

**Comment by ogaclejapan** [comment]
Hi, @ashishjain002 

Of course, You can use the [TabProvider](https://github.com/ogaclejapan/SmartTabLayout#how-to-customize-the-tab), you can customize the generation and setup of View.

**Comment by ashishjain002** [comment]
i tried it with universal image loader but didn't achieve it.....can you please help me out in this.

**Comment by ogaclejapan** [comment]
For example,
https://github.com/ogaclejapan/SmartTabLayout/blob/master/demo/src/main/java/com/ogaclejapan/smarttablayout/demo/Demo.java#L52-L74

```java

ImageView icon = (ImageView) inflater.inflate(R.layout.custom_tab_icon1, container, false);
          switch (position) {
            case 0:
              // icon.setImageDrawable(res.getDrawable(R.drawable.ic_home_white_24dp));
              Picasso.with(icon.getContext()).load("your icon url").into(icon);
              break;

```

This is an example of using the [Picasso](https://github.com/square/picasso).

**Comment by ashishjain002** [comment]
Thanks buddy.... :+1:

**Comment by ashishjain002** [comment]
its not working with Picasso too.............
its showing icons like.............
![screenshot_2015-12-01-21-20-14 1](https://cloud.githubusercontent.com/assets/16043759/11505642/85e7deea-9871-11e5-9c54-e8a0540fef55.png)

**Comment by ashishjain002** [comment]
this is the icon url : https://jenkins-assembler.googlecode.com/files/griffon-icon-48x48.png
and code is like:
	
```
CUSTOM_TAB_ICONS1(R.string.demo_title_custom_tab_icons1, R.layout.demo_custom_tab_icons1) {
		@Override
		public int[] tabs() {
			return new int[] { R.string.demo_tab_no_title, R.string.demo_tab_no_title, R.string.demo_tab_no_title, R.string.demo_tab_no_title, R.string.demo_tab_no_title, R.string.demo_tab_no_title, R.string.demo_tab_no_title, R.string.demo_tab_no_title };
		}

		@Override
		public void setup(SmartTabLayout layout) {
			super.setup(layout);

			final LayoutInflater inflater = LayoutInflater.from(layout.getContext());
			final Resources res = layout.getContext().getResources();

			layout.setCustomTabView(new SmartTabLayout.TabProvider() {
				@Override
				public View createTabView(ViewGroup container, int position, PagerAdapter adapter) {
					ImageView icon = (ImageView) inflater.inflate(R.layout.custom_tab_icon1, container, false);
					Picasso.with(icon.getContext()).load(DemoActivity.ic_url).into(icon);
					return icon;
				}
			});
		}
	},
```

**Comment by ogaclejapan** [comment]
Hi, @ashishjain002 

My demo application does not have to set the permissions.
But, Picasso is required `android.permission.INTERNET`.
https://github.com/Pixate/picasso/blob/master/picasso-sample/AndroidManifest.xml#L11

**Comment by ashishjain002** [comment]
i already gave all the permission in that manifest.
i.e. 
```
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
```
still it just shows a blank icon nothing else...............

Please try it out........
