### ISSUE TITLE
How can I use this programmatically without using XML inflation

### ISSUE THREAD

**Issue by appearance** [ogaclejapan/SmartTabLayout#103]
I am using this in my adobe native extension ANE for android. It crashes at runtime when view is getting inflated with XML layout resource id, saying that failed to find styleable attribute. How can use this entirely through programmatically instead of XML layout.
Thanks.

**Comment by ogaclejapan** [comment]
Hi, @appearance 
Sorry, some of the parameters can not be specified from the programmatically.
