### ISSUE TITLE
Bug When I pop backstack 

### ISSUE THREAD

**Issue by kazixma** [ogaclejapan/SmartTabLayout#104]
When I pop backstack of fragments and smarttablayout in this fragment then I try to open this fragment again smart tab layout is not reset to first and not clear cache . I want to clear cache of smart tab layout, How I do ?

Thank you so much and sorry for bad english.

**Comment by Phoenix000** [comment]
Me too. I build a navigation drawer with 4 items for example but when I returned to first item smart tab layout didn't reset. Why?

**Comment by ogaclejapan** [comment]
Hi, @kazixma @Phoenix000 

Do you use the [Fragment#getChildFragmentManager](http://developer.android.com/reference/android/support/v4/app/Fragment.html#getChildFragmentManager) ?
This problem will occur if you are using the [Fragment#getFragmentManager](http://developer.android.com/reference/android/support/v4/app/Fragment.html#getFragmentManager()).

If using fragment inside a ViewPager, Must be use `getChildFragmentManager`.

```java
// BAD
FragmentPagerItemAdapter adapter = new FragmentPagerItemAdapter(
  getFragmentManager(), FragmentPagerItems.with(getContext())
  .add(...)
  .create());

// GOOD
FragmentPagerItemAdapter adapter = new FragmentPagerItemAdapter(
  getChildFragmentManager(), FragmentPagerItems.with(getContext())
  .add(...)
  .create());
```

It is not a bug in the SmartTabLayout : (

**Comment by Phoenix000** [comment]
Thank you very much

**Comment by Phoenix000** [comment]
For design can you add ripple drawable for lower api in tabs when this are
pressed?

**Comment by ogaclejapan** [comment]
Hi, @Phoenix000 

It is possible if customize the tab. 
https://github.com/ogaclejapan/SmartTabLayout#how-to-customize-the-tab

**Comment by JoaoArmandoo** [comment]
thanks for this solution!

**Comment by JulyanMayer** [comment]
> Hi, @kazixma @Phoenix000
> 
> Do you use the [Fragment#getChildFragmentManager](http://developer.android.com/reference/android/support/v4/app/Fragment.html#getChildFragmentManager) ? This problem will occur if you are using the [Fragment#getFragmentManager](http://developer.android.com/reference/android/support/v4/app/Fragment.html#getFragmentManager%28%29).
> 
> If using fragment inside a ViewPager, Must be use `getChildFragmentManager`.
> 
> ```java
> // BAD
> FragmentPagerItemAdapter adapter = new FragmentPagerItemAdapter(
>   getFragmentManager(), FragmentPagerItems.with(getContext())
>   .add(...)
>   .create());
> 
> // GOOD
> FragmentPagerItemAdapter adapter = new FragmentPagerItemAdapter(
>   getChildFragmentManager(), FragmentPagerItems.with(getContext())
>   .add(...)
>   .create());
> ```
> 
> It is not a bug in the SmartTabLayout : (

Thx <3
