### ISSUE TITLE
Fix stl_indicator size

### ISSUE THREAD

**Issue by pchauhan** [ogaclejapan/SmartTabLayout#106]
Thanks for sharing nice library.
I have to set fix  width of stl_indicator  .How can we achieve this?

Thanks
Parag

**Comment by ffts** [comment]
I hope to add this feature into SmartTabLayout , too.

https://github.com/ogaclejapan/SmartTabLayout/issues/18
I found this issue but still can't find the way to set the width of an indicator.

**Comment by ogaclejapan** [comment]
Hi, @pchauhan @ffts 
Sorry for replying late. 

If the width of the tab the same, and then the width of the indicator is constant.
If set to `app:stl_indicatorWithoutPadding=true` , it can also be the width of the indicator in size without the padding.
If you set the minWidth in tab, you can also control the minimum width.

Do you want to use in what case?

**Comment by ffts** [comment]
Hi, @ogaclejapan 
Our UI Designer want to set the indicator's width to a fiexd width , but the tabs may have different width.
If the tabs' have a fixed width I think I could set a padding to control the indicators' width.But the tab may have different width and I have no idea unless to set a fixed width of indicator ...
like this
![2015-12-11 13-43-58](https://cloud.githubusercontent.com/assets/1276568/11736792/6d6e841a-a00d-11e5-8c2a-a7fdc7e69f7f.png)
![2015-12-11 13-44-21](https://cloud.githubusercontent.com/assets/1276568/11736814/80adcebe-a00d-11e5-81a6-8de7ccf28f37.png)

**Comment by ogaclejapan** [comment]
Hi, @ffts 
Thank you for sharing your image. 

It makes sense :+1: 
PR #108  will merge, but I will slightly changed the your code.

**Comment by ffts** [comment]
@ogaclejapan 
Thank you for your help!

**Comment by ogaclejapan** [comment]
Hi, @pchauhan @ffts 

It was released now : )

**Comment by ffts** [comment]
@ogaclejapan Thanks! :+1:

**Comment by pchauhan** [comment]
@ogaclejapan Thanks for adding new futures.
Now have one more doubt like as per my project requirement i have to set indicator in left side(currently in center).
How can we achieve this?
