### ISSUE TITLE
Custom Font from asset folder to text in tabs

### ISSUE THREAD

**Issue by yasiriqbal776** [ogaclejapan/SmartTabLayout#112]
We can set custom layout to SmartTabLayout in which we can set textview with different properties but when we want to apply font file to that textview then their is no option which just call function and new font is applied to textview in tabs

**Comment by ogaclejapan** [comment]
Hi, @yasiriqbal776 

There are no plans to implement the feature.
Please use the custom layout.
I recommend [Calligraphy](https://github.com/chrisjenx/Calligraphy).
