### ISSUE TITLE
How to set disable indicator selected any position?

### ISSUE THREAD

**Issue by kazixma** [ogaclejapan/SmartTabLayout#113]
I want to set disable indicator selected any position and disable scroll in tab layout . And not selected every position in smart tab layout

Thank you Sir

**Comment by ogaclejapan** [comment]
Hi, @kazixma 
Sorry, I’m not sure...

>I want to set disable indicator selected any position

do you want invisible the indicator ? or
do you want to not move the position of the indicator?

>disable scroll in tab layout

It does not scroll in tab layout when you swipe the ViewPager?

**Comment by kazixma** [comment]
@ogaclejapan  
I want  to disable all function thus
1. invisible indicator
2. not move position of the indicator
3. not scroll in the smart tab layout
4. not scroll view pager
5. disable selected each tab in smart tab layout

Thank you

**Comment by ogaclejapan** [comment]
Sorry, there are no plans to implement.
Please to pull request if you can implement :+1:
