### ISSUE TITLE
Unable to Set Custom Icon

### ISSUE THREAD

**Issue by Jayvd** [ogaclejapan/SmartTabLayout#118]
This is a lovely library. Thanks for providing them.

Arigato!

Btw, I have been trying to create a custom icon following the project, but it doesnt seem to be working.

***tab_bar_icon.xml***

    <?xml version="1.0" encoding="utf-8"?>
    <ImageView
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="?attr/selectableItemBackground"
        android:scaleType="center"
        />

and in the activity

        SmartTabLayout viewPagerTab = (SmartTabLayout) findViewById(R.id.viewPagerTab);
        viewPagerTab.setViewPager(viewPager);
           viewPagerTab.setCustomTabView(new SmartTabLayout.TabProvider() {
            @Override
            public View createTabView(ViewGroup container, int position, PagerAdapter adapter) {
                ImageView icon = (ImageView) LayoutInflater.from(viewPagerTab.getContext()).inflate(R.layout.tab_bar_icon_view,container, false);
                switch (position) {
                    case 0:
                        icon.setImageDrawable(ContextCompat.getDrawable(viewPagerTab.getContext(), R.drawable.cool_icon));
                        break;
                    case 1:
                        icon.setImageDrawable(ContextCompat.getDrawable(viewPagerTab.getContext(), R.drawable.delete_icon));
                        break;
                    case 2:
                        icon.setImageDrawable(ContextCompat.getDrawable(viewPagerTab.getContext(), R.drawable.user_icon));
                        break;
                    case 3:
                        icon.setImageDrawable(ContextCompat.getDrawable(viewPagerTab.getContext(), R.drawable.profile_icon));
                        break;
                    default:
                        throw new IllegalStateException("Invalid position: " + position);
                }
                return icon;
            }
        });

But it still deosnt work, it keep showing the titles instead.

Any thing I am missing here?

**Comment by ogaclejapan** [comment]
Hi, @Jayvd 
Thank you for using this library : )

There is a need to call `SmartTabLayout#setCustomTabView` before calling `SmartTabLayout#setViewPager `.

**Comment by stathisandr** [comment]
on setCustomTabView what i have to pass a parameter to change it to custom tab icon?
