### ISSUE TITLE
Unable to show tabs having 2 textviews

### ISSUE THREAD

**Issue by ladia12** [ogaclejapan/SmartTabLayout#121]
In case, my custom tab layout has 2 textviews, how do I use this library. Does it has this kind of support. Am I missing something?

**Comment by ogaclejapan** [comment]
Hi, @ladia12 

It no problem. 
Please show your defined layout file.

**Comment by ladia12** [comment]
Its simply a LinearLayout having 2 TextViews and a Common background color which is different when selected and when not selected

**Comment by ogaclejapan** [comment]
It no problem. Please show your defined layout file...
