### ISSUE TITLE
Different behavior on Android pre-L and L device

### ISSUE THREAD

**Issue by bradhawk** [ogaclejapan/SmartTabLayout#122]
Hi, thanks for great library.
I'm having activity that have Title bar and put SmartTabLayout on fragment, so SmartTabLayout will disappear when I replace the fragment that holds SmartTabLayout. But I having different behavior on pre-L and L device. I already test it on Genymotion and my phone which is L device.

![image](https://cloud.githubusercontent.com/assets/4829378/12472756/7605837c-c046-11e5-8143-bb70e0f8f3b0.png)
Result on L device

![image](https://cloud.githubusercontent.com/assets/4829378/12472829/12b62352-c047-11e5-902b-150565f34496.png)

Result on pre-L device

The result I'm expecting is on pre-L device.

Thank you.

**Comment by bradhawk** [comment]
problem solved. Apparently I'm using wrong implementation of fragment xml tag.

Thank you.

**Comment by adigyran** [comment]
Can you please explain how?
