### ISSUE TITLE
Problems with tabs in fragment

### ISSUE THREAD

**Issue by burnix** [ogaclejapan/SmartTabLayout#124]
I have a navigation drawer, that has few items(that replace previous fragment). My MainActivity creates a fragment that has Sliding Tabs at start. I implement them this way: 

      @Override
       public void onAttach(Activity activity) {
          myContext = (FragmentActivity) activity;
          super.onAttach(activity);
        }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.fragment_blank, container, false);
        FragmentManager fragManager = myContext.getSupportFragmentManager();
        adapter = new FragmentPagerItemAdapter(
                fragManager, FragmentPagerItems.with(getActivity())
                .add("Каталог", Catalog.class)
                .add("Проекты", Projects.class)
                .create());

        ViewPager viewPager = (ViewPager) view.findViewById(R.id.viewpager);
        viewPager.setAdapter(adapter);

        SmartTabLayout viewPagerTab = (SmartTabLayout) view.findViewById(R.id.viewpagertab);
        viewPagerTab.setViewPager(viewPager);
        return view;
    }

So after start in works super, but after working with items of Navigation Drawer, SlidingTabBar shows nothing, swipes becomes "flowing"...

I suppose, that my problem appears because of using v4, instead of v13. So I wanna ask  you  to share a piece of code, where you implement SlidingTabBar in fragment (author gives example of v.4).

**Comment by ogaclejapan** [comment]
Hi, @burnix 

>FragmentManager fragManager = myContext.getSupportFragmentManager();

Please try using the `Fragment#getChildFragmentManager`
http://developer.android.com/intl/ja/reference/android/app/Fragment.html#getChildFragmentManager()

If you want to use the ViewPager within Fragment, you will need to use this class.

**Comment by burnix** [comment]
I tried to use getChildFragmentActivity, but still can't implement SlidingTabs
using v.4 library
![2016-01-24 23 17 45](https://cloud.githubusercontent.com/assets/12573938/12538983/be6af636-c2f0-11e5-9b9f-2f8f591cba4c.png)

and using v.13
![2016-01-24 23 13 12](https://cloud.githubusercontent.com/assets/12573938/12538984/be6c5c38-c2f0-11e5-9fbf-cfc96baa41db.png)

Please, tell what Do I do wrong?

**Comment by ogaclejapan** [comment]
Hi, @burnix 

>Utility has two types available to suit the Android support library.
>
>・utils-v4 library contains the PagerAdapter implementation class for android.support.v4.app.Fragment
>・utils-v13 library contains the PagerAdapter implementation class for android.app.Fragment
>
>The two libraries have different Android support libraries that depend, but implemented functionality is the same.

So, if you want to use the `android.support.v4.app.Fragment`, 
please use the `compile 'com.ogaclejapan.smarttablayout:utils-v4:x.x.x@aar'`

**Comment by burnix** [comment]
I actually do it, but it still doesn't  solve my problem - I can't use getChildFragmentManager(look the 2nd screen of previous answer)

**Comment by ogaclejapan** [comment]
Hi, @burnix 

Why are you inherit the `android.app.Fragment` ?
If you want to use the v4, you need to inherit from `android.support.v4.app.Fragment`.

**Comment by AnasAlsaadi** [comment]
i inherit from  android.app.Fragment and i cant inherit from  android.support.v4.app.Fragment 
what is the solution ?
