### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by MasterzYuri** [ogaclejapan/SmartTabLayout#133]
This is what happens when I scroll down: https://vid.me/e/WiHa
It only happens on Lollipop devices ( api 21 and 22 ).

    public class DrawerFrag5 extends Fragment {

    private static final String KEY_TITLE = "title";

    public static DrawerFrag5 newInstance(String title) {
        DrawerFrag5 fragment = new DrawerFrag5();

        Bundle args = new Bundle();

        args.putString(KEY_TITLE, title);
        fragment.setArguments(args);

        return (fragment);
    }

    public DrawerFrag5() {
        // Required empty public constructor
    }

    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(R.layout.tabs_layout, container, false);
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        FragmentPagerItemAdapter adapter = new FragmentPagerItemAdapter(
                getChildFragmentManager(), FragmentPagerItems.with(getActivity())
                .add("Tab1", Tab1.class)
                .add("Tab2", Tab2.class)
                .add("Tab3", Tab3.class)
                .add("Tab4", Tab4.class)
                .create());

        ViewPager viewPager = (ViewPager) view.findViewById(R.id.viewpager);      
        viewPager.setAdapter(adapter);

        SmartTabLayout viewPagerTab = (SmartTabLayout) view.findViewById(R.id.viewpagertab);
        viewPagerTab.setViewPager(viewPager);
      }
    }

The layout:

    ?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
       android:layout_width="match_parent"
       android:layout_height="match_parent"
       android:orientation="vertical"
       xmlns:app="http://schemas.android.com/apk/res-auto">

    <com.ogaclejapan.smarttablayout.SmartTabLayout
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/viewpagertab"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:clipToPadding="false"
        android:paddingLeft="4dp"
        android:paddingRight="4dp"
        android:background="@color/colorPrimary"
        app:stl_defaultTabTextColor="@color/md_white_1000"
        app:stl_defaultTabTextHorizontalPadding="18dp"
        app:stl_dividerColor="#00000000"
        app:stl_dividerThickness="5dp"
        app:stl_indicatorColor="#33000000"
        app:stl_indicatorCornerRadius="18dp"
        app:stl_indicatorInterpolation="smart"
        app:stl_indicatorGravity="center"
        app:stl_indicatorThickness="36dp"
        app:stl_underlineColor="#00000000"
        app:stl_underlineThickness="0dp"
        />

    <android.support.v4.view.ViewPager
        android:id="@+id/viewpager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        />
    </LinearLayout>

The MainActivity layout:
    
    <android.support.design.widget.CoordinatorLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/main_content"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true">    // I added this line but the same thing happens....

        <android.support.design.widget.AppBarLayout
            android:id="@+id/appbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="?attr/colorPrimary"
                android:paddingTop="@dimen/status_bar_padding"   // 24dp padding for Lillipop devices, the rest 0dp
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
                app:layout_scrollFlags="scroll|enterAlways"/>

        </android.support.design.widget.AppBarLayout>

        <FrameLayout
            android:id="@+id/frame_container"
            android:layout_width="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            android:layout_height="match_parent"/>

    </android.support.design.widget.CoordinatorLayout>

Also, how can I get rid of that line between the Toolbar and Sliding Tabs?
I tried this:  `getSupportActionBar().setElevation(0);` but it's not working.
Thanks!

**Comment by ogaclejapan** [comment]
Hi, @MasterzYuri 
I'm sorry late reply.
I’ve been busy lately at work :P

`android:paddingTop="@dimen/status_bar_padding" ` 
This code I think that it is unnecessary.
`android:fitsSystemWindows` will automatically adjust
