### ISSUE TITLE
Notification notice for tab

### ISSUE THREAD

**Issue by joomi** [ogaclejapan/SmartTabLayout#134]
Great job, thanks. 
It would be great to have a circular notification attached to the tab title.

**Comment by brittonjg** [comment]
I have had a look at implementing this myself, but it would be great if it was inbuilt!

**Comment by joomi** [comment]
Hi brittonjg

Can you share an example of how you implemented this?

**Comment by jjhesk** [comment]
+1 this is a very important feature.

**Comment by brittonjg** [comment]
@joomi afraid  I don't have any code related to SmartTabLayout directly. I actually used a Fab over the tabs bar to act as a notification symbol. Not a way I would really promote, just a quick solution.

**Comment by ogaclejapan** [comment]
Hi, @joomi 
I'm sorry late reply.
I’ve been busy lately at work :P

The layout and size of the notification is different for each project.
So, in this library offers only way to customize the tab to implementors.

DEMO app will be helpful in the way that you want to customize.

**Comment by joomi** [comment]
Hi @ogaclejapan 
Thanks for the response
I understand your concern
could you please point out a way that I could, programmatically, change the layout of a specific tab (so I could add the notification mark), and what are my options (text, color, additional element)?

TNX

**Comment by ogaclejapan** [comment]
Hi, @joomi 

Code samples have been added to the DEMO app.

Try to build a master
https://github.com/ogaclejapan/SmartTabLayout/blob/master/demo/src/main/java/com/ogaclejapan/smarttablayout/demo/DemoTabWithNotificationMarkActivity.java

**Comment by joomi** [comment]
Super cool!
I will try it out.
