### ISSUE TITLE
Infinite ViewPager

### ISSUE THREAD

**Issue by dexion** [ogaclejapan/SmartTabLayout#138]
How I can use your library with [InfiniteViewPager](https://github.com/antonyt/InfiniteViewPager)? Your library generate tab text sized `adapter.getCount()` which equals `Integer.MAX_VALUE` in infinite variant. What is the solution for infinite loop `ViewPager` with your 'SmartTabLayout'?

**Comment by ogaclejapan** [comment]
Hi, @dexion 
I'm sorry late reply.
I’ve been busy lately at work :P

This library should not be used in the Infinite.
Because all of the View is generated for the first time.
