### ISSUE TITLE
Trying to make a call of the public method right after the Fragment has been instantiated.

### ISSUE THREAD

**Issue by jjhesk** [ogaclejapan/SmartTabLayout#141]
I am trying to work with `FragmentPagerItems` and `FragmentPagerItemsAdapter`. I try to get the fragment that is just instantiated from the adapter and I wanted to make some calls from it. How do I do so? I found that is extremely hard to do any modifications on top of it because the Sparrarray was private and final. What I want to achieve is that 
Fragment A is extended from v4 fragment and right after it is instantiated I would like to make a call on A for example `mA.setSometingtoWork(...)`. How do I work with it?

**Comment by ogaclejapan** [comment]
Hi, @jjhesk 
I'm sorry late reply.
I’ve been busy lately at work :P

You should call in the Fragment side?
I think you should call it by using the `Fragment#onAttach(Activity activity)` .
