### ISSUE TITLE
if want tab can zoom when selected,has any good idea?

### ISSUE THREAD

**Issue by kHRYSTAL** [ogaclejapan/SmartTabLayout#142]
Thank you :-)

**Comment by jjhesk** [comment]
+1

**Comment by ogaclejapan** [comment]
Hi, @kHRYSTAL 
I'm sorry late reply.
I’ve been busy lately at work :P

If your minSdkVersion is 21 or more, you can use the StateListAnimator
Otherwise I can not think only be set scale for each tab using the `OnPageChangeListener#onPageSelected`
