### ISSUE TITLE
Updating the bundle for a Fragment does not work

### ISSUE THREAD

**Issue by zunjae** [ogaclejapan/SmartTabLayout#143]
If I refresh my RecycleView, the content in the Fragments stay the same. I think it is because the bundles don't get updated

example code:

        Bundle firstBundle = new Bundle();
        firstBundle.putString("test", "hello");

        Bundle secondBundle = new Bundle();
        secondBundle.putString("test", "world");

        if (someBoolean) {
            title = "foo";
            bundle = firstBundle
        } else {
            title = "bar";
            bundle = secondBundle;
        }

       // Create Adapter that we will give to the ViewPager
        FragmentPagerItemAdapter adapter = new FragmentPagerItemAdapter(
                getSupportFragmentManager(), FragmentPagerItems.with(this)
                .add(title, Fragment.class, bundle)
                .create());

        // Give Adapter to ViewPager
        viewPager.setAdapter(adapter);

        // Give ViewPager to TabLayout
        smartTabLayout.setViewPager(viewPager);

I've put the code above in a method, and if I change the someBoolean value to false, the title DOES change, but the bundle stays the same

Any idea what I am doing wrong here?

**Comment by CharlesHarroch** [comment]
I've the same problem. Have you find a fix ?

**Comment by FajarKhan** [comment]
Same problem. Why updating Bundle not changing Fragment value?  

@zunjae @ogaclejapan Any solutions?

**Comment by FajarKhan** [comment]
If anyone still having the same issues. 
use `FragmentStatePagerItemAdapter` instead of `FragmentPagerItemAdapter`
