### ISSUE TITLE
custom tab with icon and text

### ISSUE THREAD

**Issue by asadwaheed1** [ogaclejapan/SmartTabLayout#144]
from issue no #34 I got the icon and text. now how do I change color of text and change image on selected tab? Thanks

**Comment by ZinoKader** [comment]
I can't figure this out either

**Comment by ogaclejapan** [comment]
Hi, @asadwaheed1 
I'm sorry late reply.
I’ve been busy lately at work :P

Added a sample for changing the color of the image and text of the selected icon :+1: 
https://github.com/ogaclejapan/SmartTabLayout/commit/91bb35a0719049f138057d835e85b8921c98fe0c

**Comment by asadwaheed1** [comment]
I don't want to change color of the image. I want to change the image. Can this happen?

**Comment by ogaclejapan** [comment]
Hi, @asadwaheed1 

Try drawable selector.
https://github.com/ogaclejapan/SmartTabLayout/blob/master/demo/src/main/res/drawable/custom_icon.xml
