### ISSUE TITLE
how can set text upon tabindicator?

### ISSUE THREAD

**Issue by MarnonLee** [ogaclejapan/SmartTabLayout#145]
when I set "app:stl_defaultTabBackground" in darkcolor ,the indicator is under tabbackground,
 but if I set "app:stl_drawDecorationAfterTab="true"",the tab_text will under indicator,how can I fix that?

**Comment by ogaclejapan** [comment]
Hi, @MarnonLee 
I'm sorry late reply.
I’ve been busy lately at work :P

`app:stl_defaultTabBackground` should be used as a touch feedback.
So, if you want to paint a single(no selector) color, it should be specified in the background of the SmartTabLayout.

```
<com.ogaclejapan.smarttablayout.SmartTabLayout
    ...
    android:background="@color/darkcolor"
    ...
```
