### ISSUE TITLE
Problem with smarttab?

### ISSUE THREAD

**Issue by zonorion** [ogaclejapan/SmartTabLayout#147]
Hi all,
I used smarttablayout in my app.
[http://i.stack.imgur.com/BTtfx.png](url)
When i run app, Fragment TIN TUC and XEM DIEM be created. Now i want when i run app, only Fragment TIN TUC be created.

Could you tell me how can i custom it?
Thanks so much.

**Comment by ogaclejapan** [comment]
Hi, @zonorion 

The link is not found.
Can you upload again?

**Comment by zonorion** [comment]
Sr, you can copy my link and paste to browser, don't click .

**Comment by ogaclejapan** [comment]
Hi, @zonorion 
Oh.. sorry I saw it now.

Set the `ViewPager#setAdapter(...)` only in Fragment of TIN TUC
And, set to `SmartTabLayout#setViewPager(...)`

Set the adapter again by the addition of XEM DIEM when the XEM DIEM is needed.
Set the `ViewPager#setAdapter(...)` in Fragment TIN TUC and XEM DIEM
And, set to `SmartTabLayout#setViewPager(...)`

How about this?
