### ISSUE TITLE
There appears a white view at the top of action bar in lollipop devices.

### ISSUE THREAD

**Issue by Bishalsingh** [ogaclejapan/SmartTabLayout#148]
![905665_218630418492056_4669175508056319158_o](https://cloud.githubusercontent.com/assets/7859556/13844584/9f14df54-ec62-11e5-8709-b4a3b36c1c4f.jpg)

**Comment by ogaclejapan** [comment]
Hi, @Bishalsingh 

Is this library to be related problem?
I do not know the position of the tab.
Please share code.
