### ISSUE TITLE
call pageadapter notifydatasetchange will not update the tab layout.

### ISSUE THREAD

**Issue by jiqimaogou** [ogaclejapan/SmartTabLayout#15]

**Comment by ogaclejapan** [comment]
Hi, @jiqimaogou 
Thank you for reporting.

It is not supported in the current version.
So, please manually call the `SmartTabLayout#setViewPager(...)` again.

I'll try to implement in the near future :)

**Comment by jiqimaogou** [comment]
ok, thank you
