### ISSUE TITLE
How to add ripple effect in onclicklistener??

### ISSUE THREAD

**Issue by sawal99** [ogaclejapan/SmartTabLayout#151]

**Comment by ogaclejapan** [comment]
Hi, @sawal99 
I'm sorry late reply.
I’ve been busy lately at work :P

It was already resolved?

Please use the `app:stl_defaultTabBackground="?attr/selectableItemBackground"`
Only API level 21 or more use the ripple sample, please click here to reference.

drawable:
https://github.com/google/iosched/blob/master/android/src/main/res/drawable/schedule_item_touchoverlay.xml

drawable-v21:
https://github.com/google/iosched/blob/master/android/src/main/res/drawable-v21/schedule_item_touchoverlay.xml
