### ISSUE TITLE
stl_defaultTabTextColor not working

### ISSUE THREAD

**Issue by NhenDen** [ogaclejapan/SmartTabLayout#154]
Hello,
I set 
app:stl_defaultTabTextColor="##FFFFFF"
but text in tab not color white.
help me, please :(

**Comment by ogaclejapan** [comment]
Hi, @NhenDen 
I'm sorry late reply.
I’ve been busy lately at work :P

It was already resolved?

Try it
```
app:stl_defaultTabTextColor="#FFFFFF"
```
