### ISSUE TITLE
Smart Tab Layout Images Tab

### ISSUE THREAD

**Issue by ghost** [ogaclejapan/SmartTabLayout#155]
Hi!
How can I implement the smart tab with icons?
Thanks

**Comment by Phoenix000** [comment]
Hi oraclejapan!
I am that ghost.
Can you help ne please?

**Comment by jjhesk** [comment]
i think u can set the custom tab layout id into the xml settings

**Comment by ogaclejapan** [comment]
Hi, @Phoenix000 
I'm sorry late reply.
I’ve been busy lately at work :P

Please look at the demo app.
https://github.com/ogaclejapan/SmartTabLayout/blob/master/demo/src/main/java/com/ogaclejapan/smarttablayout/demo/Demo.java#L46-76

@jjhesk Thank you for help : )

**Comment by Phoenix000** [comment]
Thank you very much ;-)
