### ISSUE TITLE
Scrollview not working in SmartTabLayout

### ISSUE THREAD

**Issue by NhenDen** [ogaclejapan/SmartTabLayout#157]
Hello ogaclejapan,
I can't scroll when smartTabLayout in Scrollview. I don't find bug in my code. You help me :(

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/colorWhite"
    android:descendantFocusability="beforeDescendants"
    android:focusableInTouchMode="true"
    android:gravity="center"
    android:orientation="vertical">

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginBottom="@dimen/PADDING_APP"
        android:layout_marginLeft="@dimen/PADDING_APP"
        android:layout_marginRight="@dimen/PADDING_APP"
        android:layout_marginTop="@dimen/PADDING_APP"
        android:fillViewport="true"
        android:scrollbars="none">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <LinearLayout
                android:id="@+id/fragment_login_imgCover"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical">

                <ImageView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="@drawable/logo" />

                <View
                    android:layout_width="match_parent"
                    android:layout_height="1dp"
                    android:layout_marginTop="-49dp"
                    android:alpha="0.3"
                    android:background="@color/colorWhite" />

            </LinearLayout>

            <com.ogaclejapan.smarttablayout.SmartTabLayout
                android:id="@+id/fragment_home_viewpagertab"
                android:layout_width="match_parent"
                android:layout_height="48dp"
                android:layout_marginTop="-48dp"
                android:background="@null"
                app:stl_clickable="true"
                app:stl_customTabTextLayoutId="@layout/tab_item_home"
                app:stl_customTabTextViewId="@+id/tab_item_home_textView"
                app:stl_defaultTabBackground="?attr/selectableItemBackground"
                app:stl_defaultTabTextAllCaps="false"
                app:stl_defaultTabTextColor="@color/colorTextDemo"
                app:stl_defaultTabTextHorizontalPadding="16dp"
                app:stl_defaultTabTextMinWidth="40dp"
                app:stl_defaultTabTextSize="12sp"
                app:stl_distributeEvenly="false"
                app:stl_dividerColor="@android:color/transparent"
                app:stl_dividerThickness="1dp"
                app:stl_drawDecorationAfterTab="true"
                app:stl_indicatorColor="@color/colorHighlight"
                app:stl_indicatorCornerRadius="2dp"
                app:stl_indicatorGravity="bottom"
                app:stl_indicatorInFront="false"
                app:stl_indicatorInterpolation="smart"
                app:stl_indicatorThickness="3dp"
                app:stl_indicatorWithoutPadding="false"
                app:stl_overlineColor="@android:color/transparent"
                app:stl_overlineThickness="0dp"
                app:stl_titleOffset="auto_center"
                app:stl_underlineColor="@android:color/transparent"
                app:stl_underlineThickness="1dp" />

            <android.support.v4.view.ViewPager
                android:id="@+id/fragment_home_viewpager"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

        </LinearLayout>

    </ScrollView>

</LinearLayout>

**Comment by ogaclejapan** [comment]
Hi, @NhenDen 
I'm sorry late reply.
I’ve been busy lately at work :P

It is already resolved?

I tried simple layout. 
Scrollview and SmartTabLayout works.

```java
<ScrollView
  xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:fillViewport="true"
  android:scrollbars="none"
  >

  <LinearLayout
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@color/white"
    >

    <LinearLayout
      android:id="@+id/header"
      android:orientation="vertical"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      >

      <android.support.v7.widget.Toolbar
        android:id="@id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/transparent"
        android:minHeight="?attr/actionBarSize"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
        app:theme="@style/ThemeOverlay.AppCompat.Light"
        >

      </android.support.v7.widget.Toolbar>

    </LinearLayout>

    <com.ogaclejapan.smarttablayout.SmartTabLayout
      android:id="@+id/tab"
      android:layout_width="match_parent"
      android:layout_height="48dp"
      />

    <android.support.v4.view.ViewPager
      android:id="@id/viewpager"
      android:layout_width="match_parent"
      android:layout_height="3600dp"
      />

  </LinearLayout>

</ScrollView>

```
