### ISSUE TITLE
Tabs with icons

### ISSUE THREAD

**Issue by Kondenko** [ogaclejapan/SmartTabLayout#16]
Hello. How to make tabs with icons? I try this way, but tabs keep showing text titles.

SomeActivity.java

        final LayoutInflater inflater = LayoutInflater.from(viewPagerTab.getContext());
        final Resources res = viewPagerTab.getContext().getResources();

        viewPagerTab.setCustomTabView(new SmartTabLayout.TabProvider() {
            @Override
            public View createTabView(ViewGroup container, int position, PagerAdapter 
                ImageView icon = (ImageView) inflater.inflate(R.layout.layout_tab_icon, container, false);
                switch (position) {
                    case 0:
                        icon.setImageDrawable(res.getDrawable(R.drawable.ic_group_white_24dp));
                        break;
                    case 1:
                        icon.setImageDrawable(res.getDrawable(R.drawable.ic_notifications_white_24dp));
                        break;
                    default:
                        throw new IllegalStateException("Invalid position: " + position);
                }
                return icon;
            }
        });

layout_tab_icon.xml

     <?xml version="1.0" encoding="utf-8"?>
     <com.ogaclejapan.smarttablayout.demo.TintableImageView
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:scaleType="center"
        android:background="?attr/selectableItemBackground"
        app:tint="@color/custom_tab_icon"
        />

**Comment by ogaclejapan** [comment]
Hi, @Kondenko 

Do you call `setCustomTabView(...)` before calling `setViewPager(...)`?

Tab will have been generated when you set the ViewPager to setViewPager.
So, if you do not call before, Maybe tab of the text is displayed.

**Comment by Kondenko** [comment]
I changed the code as you advised and it works now. Thanks.
