### ISSUE TITLE
How can we change tab text color unselected?

### ISSUE THREAD

**Issue by yuri4031** [ogaclejapan/SmartTabLayout#161]

**Comment by ogaclejapan** [comment]
Hi, @yuri4031 

Please refer to the demo application.
You can use the color selector.
https://github.com/ogaclejapan/SmartTabLayout/blob/master/demo/src/main/res/color/custom_tab.xml

```xml
<com.ogaclejapan.smarttablayout.SmartTabLayout
  ...
  app:stl_defaultTabTextColor="@color/custom_tab"
  ...
```
