### ISSUE TITLE
Black circle indicator on Custom Tab Circle sample for Samsung Galaxy S Duos GT-S7562

### ISSUE THREAD

**Issue by cosic** [ogaclejapan/SmartTabLayout#162]
I have a [Samsung Galaxy S Duos GT-S7562](http://www.samsung.com/ru/consumer/mobile-devices/smartphones/galaxy-s/GT-S7562ZKASER) with Android 4.0.4 that has a interesting feature: the system default color equals to `android:color/black` instead of `android:color/transparent` as usual. 

What I mean:
![device-2016-05-04-113727](https://cloud.githubusercontent.com/assets/2806586/15005403/de2441d2-11e5-11e6-92cd-4bcc78ab5fed.png)
![device-2016-05-04-113651](https://cloud.githubusercontent.com/assets/2806586/15005401/db123242-11e5-11e6-857e-29e2a876fa84.png)

I suppose to fix this issue you should add `<solid android:color="@android:color/transparent"/>` into `custom_circle` to get:

```
<?xml version="1.0" encoding="utf-8"?>
<shape
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:shape="oval"
  >

  <solid android:color="@android:color/transparent"/>

  <stroke
    android:width="1dp"
    android:color="@color/icon_disabled"
    />
</shape>
```

**Comment by ogaclejapan** [comment]
Merged now
