### ISSUE TITLE
not work  in fragment.xml

### ISSUE THREAD

**Issue by yanchengdeng** [ogaclejapan/SmartTabLayout#165]
when I user  SmartTabLayout  (with android.support.v4.view.ViewPager ) in V4.Fragment ,it's not work,but when I put  SmartTabLayout  (with android.support.v4.view.ViewPager )  in FragmentActivity  ,it works well

**Comment by MarcinOrlowski** [comment]
I'd suggest you to include snippets from your code and layout

**Comment by ogaclejapan** [comment]
Hi, @yanchengdeng 

Please show me your code and layout.

**Comment by yanchengdeng** [comment]
THX,I have  got it!  when I use the SmartTabLayout in fragment  【call  this:  FragmentPagerItemAdapter adapter = new FragmentPagerItemAdapter(
                getChildFragmentManager(), FragmentPagerItems.with(getContext())】
