### ISSUE TITLE
Troubles with positioning on MIUI

### ISSUE THREAD

**Issue by Bringoff** [ogaclejapan/SmartTabLayout#166]
I use this lib in my project to display custom tabs. All is ok with stock Android ([screenshot](https://habrastorage.org/files/52c/9f1/45e/52c9f145e28149f68934c5ef893e4d73.png)). But on MIUI active tab indicator moves out of the bottom of the screen ([screenshot](https://habrastorage.org/files/377/6d3/0c1/3776d30c1396462785477ce405e996b6.png)). My layout looks like this:

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".activity.HostActivity">

    <android.support.v4.view.ViewPager
        android:id="@+id/pager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/pagerTabLayout" />

    <com.ogaclejapan.smarttablayout.SmartTabLayout
        android:id="@id/pagerTabLayout"
        style="@style/BottomNavigationTabs"
        android:layout_alignParentBottom="true" />
    </RelativeLayout>

Tabs style is here:

    <style name="BottomNavigationTabs">
        <item name="android:layout_width">match_parent</item>
        <item name="android:layout_height">@dimen/main_tab_height</item>
        <item name="android:background">@color/colorBottomNavigation</item>
        <item name="stl_indicatorWidth">@dimen/main_tabs_indicator_width</item>
        <item name="stl_indicatorThickness">@dimen/main_tabs_indicator_height</item>
        <item name="stl_indicatorInterpolation">linear</item>
        <item name="stl_indicatorColor">@color/colorBottomNavigationIndicator</item>
        <item name="stl_drawDecorationAfterTab">true</item>
        <item name="stl_dividerThickness">@dimen/zero_size</item>
        <item name="stl_distributeEvenly">true</item>
    </style>
So, I assume that it could be a bug in MIUI, but... It's android and it's life:) I must support it and deal with this. So, I think the lib have to support MIUI.

**Comment by ogaclejapan** [comment]
Hi, @Bringoff 

SmartTabLayout settings are not a problem.
May be it a bug in MIUI.

Hmm...
Did you try a LinearLayout ?

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:orientation="vertical"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  >

  <android.support.v4.view.ViewPager
    android:id="@+id/pager"
    android:layout_width="match_parent"
    android:layout_height="0dp"
    android:layout_weight="1"
    />

  <com.ogaclejapan.smarttablayout.SmartTabLayout
    android:id="@+id/pagerTabLayout"
    style="@style/BottomNavigationTabs"
    />

</LinearLayout>
```

**Comment by Bringoff** [comment]
Yes, I did try it, but nothing changed.

**Comment by ogaclejapan** [comment]
Hmmm, How is other apps?
Did you see the same issue for other apps?

@Bringoff 
Sorry, I have no idea :(

**Comment by Bringoff** [comment]
> Did you see the same issue for other apps?

Looks like no.

**Comment by Bringoff** [comment]
Funny. I have updated my filmware and this problem is gone
