### ISSUE TITLE
Swipe direction in ViewPagers with support RTL is wrong

### ISSUE THREAD

**Issue by tux-world** [ogaclejapan/SmartTabLayout#168]
hi. in this library tabs can be support RTL and swipe that, but in this mode view pager swipe is left to right, that must be right to left

[See this screen shot](http://s6.uplod.ir/i/00775/720hzcux1rt8.png)

**Comment by ogaclejapan** [comment]
Hi, @tux-world 

There is the problem with ViewPager.
https://code.google.com/p/android/issues/detail?id=56831
