### ISSUE TITLE
WebView inside Viewpager?

### ISSUE THREAD

**Issue by AlexioVay** [ogaclejapan/SmartTabLayout#169]
How to implement a webview inside the viewpager with the functionality swiping trough all pages and loading another html file each page?

**Comment by ogaclejapan** [comment]
Hi, @AlexioVay 
I'm sorry late reply.
I’ve been busy lately at work :P

Try webview in fragment.
http://stackoverflow.com/questions/31159149/using-webview-in-fragment

You can load each url if it put url in argument of fragment 👍 

```java
FragmentPagerItemAdapter adapter = new FragmentPagerItemAdapter(
        getSupportFragmentManager(), FragmentPagerItems.with(this)
        .add(R.string.title, WebPageFragment.class, new Bundler().putString("url", "http://foo").get()),
        .add(R.string.title, WebPageFragment.class, new Bundler().putString("url", "http://bar").get())
        .create());

viewPager.setAdapter(adapter);
```

**Comment by AllanWang** [comment]
Just started programming, but I've incorporated webviews as well as this viewpager. If you want a full sample fragment, check this:

https://github.com/AllanWang/Facebook-Frost/blob/master/app/src/main/java/com/pitchedapps/facebook/frost/fragments/NewsFeedFragment.java

**Comment by harsh85** [comment]
my website = https://tyrosx.com
what is API?
