### ISSUE TITLE
how can I set the width of each item of the tab

### ISSUE THREAD

**Issue by peterforme** [ogaclejapan/SmartTabLayout#171]
for example , in my smartTabLayout there are 10 fragments ,  so there are 10 titles in the tab.
Now title 1 is too far away from title 2, I want to **make each title closer** , what should I do

**Comment by ogaclejapan** [comment]
Hi, @peterforme 
I'm sorry late reply.
I’ve been busy lately at work :P

Try custom layout if you want to set `maxLength` of TextView.

[demo_custom_tab_text.xml](https://github.com/ogaclejapan/SmartTabLayout/blob/master/demo/src/main/res/layout/demo_custom_tab_text.xml)

```xml
<com.ogaclejapan.smarttablayout.SmartTabLayout
  ...
  app:stl_customTabTextLayoutId="@layout/custom_tab"
  app:stl_customTabTextViewId="@id/custom_text"
  ...
  />
```

[custom_tab.xml](https://github.com/ogaclejapan/SmartTabLayout/blob/master/demo/src/main/res/layout/custom_tab.xml)

```xml
<TextView
   ...
   android:maxLength="xxx"
   ...
   />
```

Or, Try custom tab provider if you want to full customize the tab of each title.

https://github.com/ogaclejapan/SmartTabLayout/blob/master/demo/src/main/java/com/ogaclejapan/smarttablayout/demo/Demo.java#L52-L74
