### ISSUE TITLE
have some attr can fill the gravity?

### ISSUE THREAD

**Issue by zhougonglai** [ogaclejapan/SmartTabLayout#172]
![qq20160527-0 2x](https://cloud.githubusercontent.com/assets/10954751/15596676/e48b916a-23fb-11e6-97b2-b9fbec44b984.png)

like the title!

**Comment by ogaclejapan** [comment]
Hi, @zhougonglai 

Try this.

```
<com.ogaclejapan.smarttablayout.SmartTabLayout
    ...
    app:stl_distributeEvenly="true"
    ...
```
