### ISSUE TITLE
notification count

### ISSUE THREAD

**Issue by VeeraAndroid** [ogaclejapan/SmartTabLayout#173]
It possible to create and update notification count (**badge count**)

**Comment by lorcanluo** [comment]
i need too

**Comment by ogaclejapan** [comment]
Hi, @VeeraAndroid @lorcanluo 

https://github.com/ogaclejapan/SmartTabLayout/issues/134

The layout and size of the notification is different for each project.
So, I’m not going to add the notification badge.
