### ISSUE TITLE
How can I change the width of the indicator?

### ISSUE THREAD

**Issue by soapsign** [ogaclejapan/SmartTabLayout#18]
How can I change the width of the indicator?

**Comment by Duncan00** [comment]
Same question here~ I want to align a shorter line indicator in the middle of the tab too~ Thanks~

**Comment by ogaclejapan** [comment]
Hi, @soapsign @Duncan00 
Sorry to reply late.

It can not be shorter than tab in the current implementation.
Try to consider the future of the implementation. 

Thanks.

**Comment by ogaclejapan** [comment]
Hi, @soapsign @Duncan00 

Right now, we have released the 1.2.0.
It contains changes that you can customize the indicator.
