### ISSUE TITLE
Gradle error

### ISSUE THREAD

**Issue by Polyterative** [ogaclejapan/SmartTabLayout#184]
I'm getting this error since yesterday: https://goo.gl/S91bQo
Please can anyone help me? I tried cleaning project, rebuild project, invalidate caches/restart, gradle sync.
What to do?

**Comment by Polyterative** [comment]
"Solved" by not using the library...

**Comment by syntaxhr** [comment]
@Polyterative It seems like you have a Dex error (your number of methods is bigger than 64k).
More information here: https://developer.android.com/studio/build/multidex.html
