### ISSUE TITLE
How can I dynamic change the tabs?

### ISSUE THREAD

**Issue by wingfordream** [ogaclejapan/SmartTabLayout#19]

**Comment by ogaclejapan** [comment]
Hi, @wingfordream 
Is the same question? -> #15

It will be changed to re-set the ViewPager.
`SmartTabLayout#setViewPager(...)`

**Comment by ogaclejapan** [comment]
Hi, @wingfordream 

Is this issue solved?

**Comment by ogaclejapan** [comment]
It closed it because the no response.
