### ISSUE TITLE
Indicator Thickness Trik 1 

### ISSUE THREAD

**Issue by a-elhaddad** [ogaclejapan/SmartTabLayout#196]
where is the implementation of Indicator Thickness Trik 1  i searched in Demo but didn't find it .

Sorry i find it .

**Comment by kaustav07** [comment]
I can't find it..where is it?

**Comment by Kondenko** [comment]
If anyone's looking for it, it's [here](https://github.com/ogaclejapan/SmartTabLayout/blob/master/demo/src/main/res/layout/demo_indicator_trick1.xml)
