### ISSUE TITLE
Tab Background Color

### ISSUE THREAD

**Issue by HosseinA** [ogaclejapan/SmartTabLayout#214]
how can I change the background color in your library?! there is no example and it's always matches with primary color...
will be appreciated if you can help me out.
Best Regards

**Comment by freundyotam** [comment]
`android:background="@color/your_color"` This will give you the same background color for all tabs.

**Comment by RockyLin** [comment]
@freundyotam How to set ColorStateList to the background of all tabs?  Thanks!
