### ISSUE TITLE
add fragment dynamically

### ISSUE THREAD

**Issue by AAmeriyan** [ogaclejapan/SmartTabLayout#231]
how can I add fragment dynamically into FragmentPagerItemAdapter for example in a loop?

**Comment by aldiferdiyan** [comment]
this work for me 

`

        FragmentPagerItems dynamicFragment = FragmentPagerItems.with(this).create();
        for (int i = 0; i < 5; i++) {
            dynamicFragment.add(FragmentPagerItem.of("Dynamic Fragment ", HargaDetail.class));
        }
        
       adapter = new FragmentPagerItemAdapter(getSupportFragmentManager(),dynamicFragment);

        ViewPager viewPager = (ViewPager) findViewById(R.id.viewpager);
        viewPager.setAdapter(adapter);

        SmartTabLayout viewPagerTab = (SmartTabLayout) findViewById(R.id.viewpagertab);
        viewPagerTab.setViewPager(viewPager);
`

**Comment by AAmeriyan** [comment]
thanks worked for me.

**Comment by gustavobrunoro** [comment]
I am using this approach but I would like to pass data from activity to fragment and I am having difficulties could help me

      dynamicFragment = FragmentPagerItems.with(this).create();
        for (int i = 0; i < 5; i++) {
            dynamicFragment.add( FragmentPagerItem.of(String.valueOf( 2014 + i ), InformeRendimentosFragment.class));
        }
        adapter = new FragmentPagerItemAdapter( getSupportFragmentManager() , dynamicFragment );
        viewPager.setAdapter( adapter );

        Bundle bundle = new Bundle();
        bundle.putInt( "teste", 1 );
        informeRendimentosFragment.setArguments(bundle);
        smartTabLayout.setViewPager( viewPager );


Fragment

@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        View view = inflater.inflate(R.layout.fragment_informe_rendimentos, container, false);

        Bundle data = new Bundle();

        int  teste= data.getInt("teste");

        Toast.makeText( getContext() , "Dados: " + String.valueOf( teste ) , Toast.LENGTH_SHORT ).show();

**Comment by spever** [comment]
Its easier ,sush as below:





FragmentPagerItems dynamicFragment = FragmentPagerItems.with(this);
    for (int i = 0; i < 5; i++) {
       Bundle args = new Bundle();
       bundle.putInt( "teste", 1 );
        dynamicFragment.add( FragmentPagerItem.of(String.valueOf( 2014 + i ), InformeRendimentosFragment.class,args));
    }
    adapter = new FragmentPagerItemAdapter( getSupportFragmentManager() , dynamicFragment );
    viewPager.setAdapter( adapter );
    smartTabLayout.setViewPager( viewPager );

**Comment by spever** [comment]
@gustavobrunoro
