### ISSUE TITLE
Only Tab Click Listener

### ISSUE THREAD

**Issue by denebasecas** [ogaclejapan/SmartTabLayout#25]
Hi sir,

I want to know if there is a way to disable the swipe of the viewpager and let enable only the tabs. I mean, I want the pages change only with a click on the tab. Is this possible?.

The reason I want to use just the click of the tabs is because of this:
![picture1](https://cloud.githubusercontent.com/assets/6497625/7714418/267c277c-fe48-11e4-85fb-ec5cfcdb70aa.png)

I want to use ViewPager as a parent, and in one of the pages have tabs. I want to know is if this possible? or if you know another way to do.

PD: The page with only tabs loads the tabs dynamically thats why I can't do many static Tabs in XML

As always, thank you for your help.

Have a nice day.

**Comment by ogaclejapan** [comment]
Hi, @denebasecas 

You need to use a customized ViewPager.
http://stackoverflow.com/questions/9650265/how-do-disable-paging-by-swiping-with-finger-in-viewpager-but-still-be-able-to-s

**Comment by denebasecas** [comment]
Thank You Sir. :D :+1:
