### ISSUE TITLE
Tab issue

### ISSUE THREAD

**Issue by sergeyfitis** [ogaclejapan/SmartTabLayout#26]
When tabHost has only two tabs, the second tab has invalid size. Its width too small.
My setup:
 - custom tabs via tabProvider
 - stl_indicatorAlwaysInCenter = true

Second tab is very short http://screencloud.net/v/uO7Z
If tabs are more than three, all is fine http://screencloud.net/v/v3hT

**Comment by ogaclejapan** [comment]
Hi, @sergeyfitis 
Thank you for reporting!

Sorry, I was going to use only if there is a large number of tabs as Newsstand google app.
So, it does not support the same reason as the following:'(

>Notes: Both 'stl_indicatorAlwaysInCenter' and 'stl_distributeEvenly' if it is set to true, it will throw UnsupportedOperationException.
