### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by ezamelczykespeo** [ogaclejapan/SmartTabLayout#271]
As of right now there are problems with working with this library with AndroidX. I suggest migrating to AndroidX namespace.

**Comment by ogaclejapan** [comment]
Thank you for your reporting.
I'm planning to v2.0 version for AndroidX

**Comment by davideas** [comment]
Please, just support the AndroidX without new features... for now.
It should take 30 mins.

**Comment by fa-hessari** [comment]
It's working fine in my app after migrating to AndroidX although android studio shows me warning about wrong arguments.for example:

`'setOnPageChangeListener(android.support.v4.view.ViewPager.OnPageChangeListener)' in 'com.ogaclejapan.smarttablayout.SmartTabLayout' cannot be applied to '(androidx.viewpager.widget.ViewPager.OnPageChangeListener)'`

**Comment by ogaclejapan** [comment]
SmartTabLayout migrated to androidx. Sorry for replying so late 🙏
