### ISSUE TITLE
tabView.getLayoutParams() is null

### ISSUE THREAD

**Issue by luyuan11233** [ogaclejapan/SmartTabLayout#296]
if (distributeEvenly) {
        LinearLayout.LayoutParams lp = (LinearLayout.LayoutParams) tabView.getLayoutParams();
        lp.width = 0;
        lp.weight = 1;
      }

      if (internalTabClickListener != null) {
        tabView.setOnClickListener(internalTabClickListener);
      }

      tabStrip.addView(tabView);
when "distributeEvenly" is true,"tabView.getLayoutParams()" get null,the answer is before "tabView.getLayoutParams()",you should set " tabStrip.addView(tabView);"

**Comment by luyuan11233** [comment]
help

**Comment by luyuan11233** [comment]
help

**Comment by makecloud** [comment]
我的解决方案，亲测有效：

this is my resolve，work right:

  tabLayout.setCustomTabView(new SmartTabLayout.TabProvider() {
            @Override
            public View createTabView(ViewGroup container, int position, PagerAdapter adapter) {
                LinearLayout.LayoutParams lp = new LayoutParams(0,0);
                tab1View.setLayoutParams(lp);
                return tab1View;
            }
        });

**Comment by makecloud** [comment]
我的解决方案，亲测有效：

this is my resolve，work right:

```java
tabLayout.setCustomTabView(new SmartTabLayout.TabProvider() {
            @Override
            public View createTabView(ViewGroup container, int position, PagerAdapter adapter) {
                LinearLayout.LayoutParams lp = new LayoutParams(MATCH_PARENT,MATCH_PARENT);
                tab1View.setLayoutParams(lp);
                return tab1View;
            }
        });
```

**Comment by makecloud** [comment]
> help

i help you.  你是中国人吗

**Comment by luyuan11233** [comment]
@makecloud 
 是啊，诸葛军师...
