### ISSUE TITLE
change text color when selected.

### ISSUE THREAD

**Issue by jiqimaogou** [ogaclejapan/SmartTabLayout#3]
How can I do let selected tab's text color is highlight
.

**Comment by ogaclejapan** [comment]
Did you look at the code of the demo?

![Image](https://raw.githubusercontent.com/ogaclejapan/SmartTabLayout/master/art/demo3.gif)

* https://github.com/ogaclejapan/SmartTabLayout/blob/master/demo/src/main/res/layout/custom_tab.xml
* https://github.com/ogaclejapan/SmartTabLayout/blob/master/demo/src/main/res/color/custom_tab.xml

**Comment by jiqimaogou** [comment]
ok, thank you, I set the defaultTextColor with colorStateList, it doesn't work. I must use custom textView.

**Comment by ogaclejapan** [comment]
defaultTextColor is not supported colorStateList.
I'll try to implement in the next version :+1: 

Thank you for reporting!
