### ISSUE TITLE
Number of tabs on screen

### ISSUE THREAD

**Issue by gerlandiya** [ogaclejapan/SmartTabLayout#31]
I appreciate your good working solution. Is it possible to set a number of tabs to be forcefully placed on the screen? I have 7 "day-of-week" tabs, and usually only 6 of them on the screen, with tabstrip scrollable. How can I make my app adjust paddings and tab size to make all 7 visible? (and, respectively, for landscape orientation or a very big screen, to limit number of tabs and to stretch only 7)
Thank you

**Comment by ogaclejapan** [comment]
Hi, @gerlandiya 

You might be able to do what you want if you can evenly arranged only when the landscape and large size using the TabProvider interface.

```java

tabLayout.setCustomTabView(new TabProvider() {
  @Override
  View createTabView(ViewGroup container, int position, PagerAdapter adapter) {
    if (landscape orientation or a very big screen) {
      return TextView (width=0dp, weight=1)
    } else {
      return TextView (normally)
    }
  }
});

```

Hrmm, I can't come up with a good idea.

**Comment by ogaclejapan** [comment]
For a long time, there is no response.
So, we will close the issue.
