### ISSUE TITLE
Misbehavior after screen rotation

### ISSUE THREAD

**Issue by khafan** [ogaclejapan/SmartTabLayout#33]
I use this library for swiping between fragments with different layouts (sth like face book app). 
After starting the app everything is OK but when I rotate the screen, fragments don't change on swipe however the current fragment containing staggered gridview library (https://github.com/etsy/AndroidStaggeredGrid)  is recreated correctly. (number of columns change)
I wonder if it's related to this library or not and can you help me solve this.

**Comment by ogaclejapan** [comment]
I can not reproduce the problem in my environment.
So, I will close this issue.

If you know how to reproduce, please create a new issue with the Steps to Reproduce.
