### ISSUE TITLE
how to edit the custom tab child element? 

### ISSUE THREAD

**Issue by hksfho** [ogaclejapan/SmartTabLayout#37]
I have custom my own TabView, there have icon, and two textview.
I want to change the textview when I change the  viewpage
just like the tab background will change when the viewpage changed.

viewPagerTab.setCustomTabView(new SmartTabLayout.TabProvider() {
			@Override
			public View createTabView(ViewGroup container, int position,
					PagerAdapter adapter) {
				RelativeLayout layout = (RelativeLayout) inflater.inflate(
						R.layout.mainactivity_tab, container, false);
				ImageView icon = (ImageView) layout
						.findViewById(R.id.activity_main_tab_iv_icon);
				TextView title = (TextView) layout
						.findViewById(R.id.activity_main_tab_tv_title);
				TextView notification = (TextView) layout
						.findViewById(R.id.activity_main_tab_tv_notification);
				switch (position) {
				case 0:
					icon.setImageDrawable(res
							.getDrawable(R.drawable.mainactivity_tab_icon_home));
					title.setText(adapter.getPageTitle(position));
					notification.setVisibility(View.GONE);
					break;
				case 1:
					icon.setImageDrawable(res
							.getDrawable(R.drawable.mainactivity_tab_icon_chart));
					title.setText(adapter.getPageTitle(position));
					notification.setVisibility(View.GONE);
					break;
				case 2:
					icon.setImageDrawable(res
							.getDrawable(R.drawable.mainactivity_tab_icon_message));
					title.setText(adapter.getPageTitle(position));
					notification.setText("13");
					break;
				case 3:
					icon.setImageDrawable(res
							.getDrawable(R.drawable.mainactivity_tab_icon_my));
					title.setText(adapter.getPageTitle(position));
					notification.setVisibility(View.GONE);
					break;
				default:
					throw new IllegalStateException("Invalid position: "
							+ position);
				}
				return layout;
			}
		});
		viewPagerTab.setViewPager(viewPager);

**Comment by hksfho** [comment]
title = (TextView) viewPagerTab.getTabAt(
						viewPager.getCurrentItem()).findViewById(
						R.id.activity_main_tab_tv_title);
				title.setTextColor(getResources().getColor(R.color.main_tab_icon_enabled));

I god it.

**Comment by ogaclejapan** [comment]
:+1: 

Even use [ColorStateList](http://developer.android.com/guide/topics/resources/color-list-resource.html) If you just change the color state of text.
Because it will be in the state of the `android:state_selected="true"` when the tab is selected.

color/custom_tab.xml:
```xml

<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:color="@color/text_enabled" android:state_selected="true"/>
  <item android:color="@color/text_disabled" android:state_selected="false"/>
</selector>

```

layout/mainactivity_tab.xml:

```xml

<?xml version="1.0" encoding="utf-8"?>

...

<TextView
    android:id="@+id/activity_main_tab_tv_title"
    ...
    android:textColor="@color/custom_tab"
    ...
    >

</TextView>

...

```
