### ISSUE TITLE
Change tab text

### ISSUE THREAD

**Issue by mynickisalreadytaken** [ogaclejapan/SmartTabLayout#40]
Please tell me
How can I change title of tab?

```
adapter = new FragmentPagerItemAdapter(getSupportFragmentManager(), FragmentPagerItems.with(AnketaActivity.this)
                .add("tab1", AnketaFragment1.class)
                .add("tab2", AnketaFragment2.class)
                .add("tab3", AnketaFragment3.class)
                .create());
```
I want change "tab1" to "tab1 new"

**Comment by ogaclejapan** [comment]
Hi, @mynickisalreadytaken 

You want to change before you set the `ViewPager#setAdapter(..)`?
Or you want to change after the tab is displayed?

Steps to change is different depending on the situation.

**Comment by mynickisalreadytaken** [comment]
after the tab is displayed

**Comment by ogaclejapan** [comment]
Okay you can easily display on the changes:

```java

((TextView)viewPagerTab.getTabAt(0)).setText("tab1 new");

```

Solved ?

**Comment by mynickisalreadytaken** [comment]
thank you!
