### ISSUE TITLE
Question regarding library

### ISSUE THREAD

**Issue by hkoueke** [ogaclejapan/SmartTabLayout#45]
Hello ogacleJapan,
I use this library daily and i wanted to know if there was a way to make it compatible with CoordinatorLayout and TabLayout, in order to hide the Toolbar when an item is scrolled in one of the tabs ( a RecyclerView in my case)...

**Comment by ogaclejapan** [comment]
Hi, @hkoueke 

SmartTabLayout it can be used in the CoordinatorLayout in the same way as TabLayout
When the [Cheesesquare](https://github.com/chrisbanes/cheesesquare) app as an example, please try to replace the part of TabLayout to SmartTabLayout.

https://github.com/chrisbanes/cheesesquare/blob/master/app/src/main/res/layout/include_list_viewpager.xml#L38-41

res/layout/include_list_viewpager.xml

```java

...

    <com.ogaclejapan.smarttablayout.SmartTabLayout
      android:id="@+id/tabs"
      android:layout_width="match_parent"
      android:layout_height="48dp"
      app:stl_defaultTabTextColor="@color/tab_text_color"
      app:stl_defaultTabTextSize="14sp"
      app:stl_distributeEvenly="true"
      app:stl_dividerThickness="0dp"
      app:stl_indicatorColor="?attr/colorAccent"
      app:stl_indicatorInterpolation="linear"
      app:stl_indicatorThickness="2dp"
      app:stl_underlineThickness="0dp"
      />
    <!--<android.support.design.widget.TabLayout-->
    <!--android:id="@+id/tabs"-->
    <!--android:layout_width="match_parent"-->
    <!--android:layout_height="wrap_content" />-->

...

```

res/color/tab_text_color.xml:

```xml

<selector xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:color="#ffffffff" android:state_selected="true"/>
  <item android:color="#b3ffffff"/>
</selector>

```

Solved ?

**Comment by hkoueke** [comment]
Solved! Thanks a lot!

**Comment by ogaclejapan** [comment]
:+1:
