### ISSUE TITLE
put gradient drawable in divider?

### ISSUE THREAD

**Issue by cabuhatprince** [ogaclejapan/SmartTabLayout#47]

**Comment by ogaclejapan** [comment]
Hi, @cabuhatprince 

It does not support.  It supports ColorDrawable only.
https://github.com/ogaclejapan/SmartTabLayout/blob/master/library/src/main/java/com/ogaclejapan/smarttablayout/SmartTabStrip.java#L134-135

Do you want to use?

**Comment by ogaclejapan** [comment]
For a long time, there is no response.
So, we will close the issue.
