### ISSUE TITLE
how can set typeface for this nice library?

### ISSUE THREAD

**Issue by saeedsh92** [ogaclejapan/SmartTabLayout#5]

**Comment by ogaclejapan** [comment]
Hi, @saeedsh92 

The default tab attribute does not support the typeface.
Try try using the layout of the custom tab.

e.g.

custom_tab_with_typeface.xm:
```xml

<?xml version="1.0" encoding="utf-8"?>
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/custom_text"
    android:layout_width="wrap_content"
    android:layout_height="match_parent"
    android:textSize="14sp"
    android:textColor="@color/custom_tab"
    android:gravity="center"
    android:paddingLeft="24dp"
    android:paddingRight="24dp"
    android:typeface="sans"
    >

</TextView>

```

tab_layout.xml:
```xml

<com.ogaclejapan.smarttablayout.SmartTabLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@id/viewpagertab"
    android:layout_width="match_parent"
    android:layout_height="@dimen/tab_height"
    ...
    app:stl_customTabTextLayoutId="@layout/custom_tab_with_type_face"
    app:stl_customTabTextViewId="@id/custom_text"
    />

```

**Comment by saeedsh92** [comment]
thank you guys , your library helped me alot ;)

**Comment by ppamorim** [comment]
Why you don't use some concepts of this library on this?

https://github.com/leonardoxh/CustomFont

**Comment by ppamorim** [comment]
@ogaclejapan This don't work with me.

Return: Error:(38, 50) No resource found that matches the given name (at 'stl_customTabTextViewId' with value '@id/custom_font').

**Comment by ogaclejapan** [comment]
Hi, @ppamorim 

Hmm,
In the same way in 'CustomTabText' of demo application makes use of the 'stl_customTabTextViewId', but the demo application running in your environment?

https://github.com/ogaclejapan/SmartTabLayout/blob/master/demo/src/main/res/layout/demo_custom_tab_text.xml

Or, Does this problem has occurred when using the CustomFont?
https://github.com/leonardoxh/CustomFont

**Comment by ppamorim** [comment]
@ogaclejapan 
I've use the same way of the demo application. 
I tried to use customFont and the simple TextView, no one works.

**Comment by ppamorim** [comment]
why you don't use anything more expressive? Look like "app:font"?

**Comment by ogaclejapan** [comment]
Hi, @ppamorim 

I tried, there is no problem in my environment.
https://github.com/ogaclejapan/SmartTabLayout/tree/issue-5

**Comment by ogaclejapan** [comment]
I am also using other custom font library within the my app.
https://github.com/ogaclejapan/Qiitanium/blob/master/qiitanium/src/main/java/com/ogaclejapan/qiitanium/presentation/activity/TopActivity.java#L107

**Comment by ogaclejapan** [comment]
I do not know why you can not use in your environment.

**Comment by ppamorim** [comment]
I try to use the base TextView but still not working.

**Comment by ppamorim** [comment]
Only attribute "stl_customTabTextViewId" don't work.

**Comment by ogaclejapan** [comment]
Thank you for testing.
Could you show your defined custom layout file?

I want to see the code for this point in your defined layout.
https://github.com/ogaclejapan/SmartTabLayout/blob/master/library/src/main/java/com/ogaclejapan/smarttablayout/SmartTabLayout.java#L438-452

**Comment by kaiyan910** [comment]
@ppamorim 
I think you are placing the SmartTabLayout inside another layout, right? (i.e. SmartTabLayout is not the root layout of the XML)
stl_customTabTextViewId only works when SmartTabLayout is a root layout so try to create a layout xml with SmartTabLayout as root layout and include the xml back to your original layout, then it works.

**Comment by ppamorim** [comment]
@kaiyan910 I could use! Relax...

**Comment by LeeeYou** [comment]
@kaiyan910 thank you so much...

**Comment by ashkanSp** [comment]
so simple:


public class MyTabLayout extends SmartTabLayout {
    public MyTabLayout(Context context) {

        super(context);
    }

    public MyTabLayout(Context context, AttributeSet attrs) {
        super(context, attrs);

    }

    public MyTabLayout(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);


    }



    @Override
    protected TextView createDefaultTabView(CharSequence title) {
        TextView myTextView = super.createDefaultTabView(title);
        myTextView.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "font/" + "iran_sans_number" + ".ttf"));
        return myTextView;
    }
}

**Comment by Dot01110011** [comment]
thx @ashkanSp !
i create "SmartTabLayoutPro.class"
in java code replace "SmartTabLayoutPro" instead "SmartTabLayout"
and in layout replace my class directory (for me is "ir.dariche.ui.SmartTabLayoutPro")  instead "com.ogaclejapan.smarttablayout.SmartTabLayout"
