### ISSUE TITLE
Seleted Title color;

### ISSUE THREAD

**Issue by risekid** [ogaclejapan/SmartTabLayout#51]
hi, this is a great lib, but I found there is no seleted title color in attributes?

**Comment by ogaclejapan** [comment]
HI, @risekid 

You can use the ColorStateList.
https://github.com/ogaclejapan/SmartTabLayout/blob/master/demo/src/main/res/color/custom_tab.xml

Solved?

**Comment by risekid** [comment]
@ogaclejapan yeah, I know, and it works, thx. But I just wonder why there is just a defaultTabTextColor in attributes.

**Comment by ogaclejapan** [comment]
@risekid Thank you for your advice.

TabLayout of design support library are also divided into two attributes.

```xml

<attr name="tabTextColor" format="color"/>
<attr name="tabSelectedTextColor" format="color"/>

```

Hmm,, I think as good, even ColorStateList, 
but, wonder if easy to use better everyone `tabTextColor` and `tabSelectedTextColor`...? :o

```xml

<attr name="stl_defaultTabTextColor" format="color|reference"/>

```

I'll consider it.
Thanks!
