### ISSUE TITLE
SmartTabLayout in bottom position

### ISSUE THREAD

**Issue by matheusfreire** [ogaclejapan/SmartTabLayout#52]
Hi everyone, congratulations for the SmartTabLayout. Helps me a lot.

My question is: Can I put SmartTab in bottom position or only in top of my view pager?

Thanks for everything.
Best Regards, Matheus

**Comment by ogaclejapan** [comment]
Hi, @matheusfreire 

Of course, it can also be displayed on the bottom of the ViewPager
Please look at the #39
