### ISSUE TITLE
Replace Fragment in view pager

### ISSUE THREAD

**Issue by GabiR** [ogaclejapan/SmartTabLayout#57]
Hi! I have 3 tabs with Fragment1, Fragment2, Fragment3.

I want to be able to replace Fragment2 with Fragment4 dynamically from Fragment2. How can I do this?

**Comment by ogaclejapan** [comment]
Hi, @GabiR 
Sorry for replying late.

Maybe it will work with this code.

onCreate: 
```java

FragmentPagerItems pages = FragmentPagerItems.with(this)
    .add("Test1", Fragment1.class)
    .add("Test2", Fragment2.class)
    .add("Test3", Fragment3.class)
    .create();

FragmentStatePagerItemAdapter adapter = new FragmentStatePagerItemAdapter(
    getSupportFragmentManager(), pages) {
  @Override
  public int getItemPosition(Object object) {
    return PagerAdapter.POSITION_NONE;
  }
};

viewPager.setAdapter(adapter);
viewPagerTab.setViewPager(viewPager);

```

Replace:
```java

pages.set(1, FragmentPagerItem.of("Test2", Fragment4.class));
adapter.notifyDataSetChanged();

```

If you want to also change the tab name, you will need to re-set the `SmartTabLayout#setViewPager(...)`
```java

pages.set(1, FragmentPagerItem.of("Test2", Fragment4.class));
adapter.notifyDataSetChanged();
viewPagerTab.setViewPager(viewPager); 

```

Solved?

**Comment by GabiR** [comment]
Yup, thanks a lot

**Comment by MarkOSullivan94** [comment]
@ogaclejapan would you be able to provide a working example of this? Trying to implement something similar and it changes the text within the tab but doesn't change the fragment displayed.
