### ISSUE TITLE
Tab title not appear

### ISSUE THREAD

**Issue by encryptgo** [ogaclejapan/SmartTabLayout#59]
There is some bug, the title of tab not appear when we create FragmentStatePagerItemAdapter in fragment after get data from server (API response).

**Comment by ogaclejapan** [comment]
Hi, @encryptgo 

Please show me the code the problem occurs.

**Comment by encryptgo** [comment]
Hi, @ogaclejapan this is the code in my fragment
FragmentPagerItemAdapter adapter = new FragmentPagerItemAdapter(
                getChildFragmentManager(), FragmentPagerItems.with(getActivity())
                .add("Tab 1", Tab1Fragment.class)
                .add("Tab 2", Tab2Fragment.class)
                .create());
        viewpager.setAdapter(adapter);
        viewPagerTab.setViewPager(viewpager);

The code above running with no problems if i put in onActivityCreated method. but get some problem (The tab title not showing ex : Tab 1) in some conditions.
1. when i put it after data request finish from server (ex : onSuccess Method in retrofit).
2. when go to new activity with fragment transaction in it.
ex : ActivityA -> call -> ActivityB where in onCreate method of ActivityB there is a fragment transaction. and in fragment i create the FragmentPagerItemAdapter like code above.

**Comment by ogaclejapan** [comment]
Hi, @encryptgo 

Is this what you mean?

>1 when i put it after data request finish from server

```java

void onActivityCreated(...) {

  somethingAsyncRequest.call(new Callback() {

    @Override
    void onSuccess(...) {

      FragmentPagerItemAdapter adapter = new FragmentPagerItemAdapter(
      getChildFragmentManager(), FragmentPagerItems.with(getActivity())
      .add("Tab 1", Tab1Fragment.class)
      .add("Tab 2", Tab2Fragment.class)
      .create());
      viewpager.setAdapter(adapter);
      viewPagerTab.setViewPager(viewpager);

    }

  });

}

```

> 2 when go to new activity with fragment transaction in it.

```java

class ActivityA {

  void onClickSomething() {
    ActivityB.startActivity(this);
  }
  
}

class ActivityB {

  void onCreate(...) {
      getSupportFragmentManager().beginTransaction()
          .add(android.R.id.content, new FragmentB())
          .commit();
  }

}

class FragmentB {

  void onCreateView(...) {
  
    ...

    FragmentPagerItemAdapter adapter = new FragmentPagerItemAdapter(
    getChildFragmentManager(), FragmentPagerItems.with(getActivity())
      .add("Tab 1", Tab1Fragment.class)
      .add("Tab 2", Tab2Fragment.class)
      .create());
    viewpager.setAdapter(adapter);
    viewPagerTab.setViewPager(viewpager);
    
    ...
    
    return root;

  }

}

```

**Comment by encryptgo** [comment]
Yes that's right! but, i have solved that case with give the delay when fragment commit.

**Comment by ogaclejapan** [comment]
Hi, @encryptgo 

Did you have a problem in this library?
I want to share how to resolve the problem.

**Comment by encryptgo** [comment]
@ogaclejapan 

Please let me know how do you resolve it.

**Comment by ogaclejapan** [comment]
Sorry, It was wrong English
I want to know your solutions. 
It means that.

**Comment by encryptgo** [comment]
1. I just put out FragmentPagerItemAdapter from onSuccess method and create as normal and inject the data from server later.
2. I just give delay in fragment transaction
Handler handler = new Handler();
handler.posDelayed(....{
// fragment transaction here
}, 300);
