### ISSUE TITLE
tab text color can change when checked?

### ISSUE THREAD

**Issue by jesielin** [ogaclejapan/SmartTabLayout#6]
i just found the default text color,could i change the text color when it checked?

**Comment by jesielin** [comment]
im sorry,i just find it..

**Comment by ogaclejapan** [comment]
Did you solve?

stl_defaultTabTextColor attribute to support ColorStateList. #3
Active tab will be selected state.

**Comment by jesielin** [comment]
yes！Thanks for your lib. brilliant code~
