### ISSUE TITLE
Tab title gone after screen sleep.

### ISSUE THREAD

**Issue by encryptgo** [ogaclejapan/SmartTabLayout#60]
Hi @ogaclejapan i have found new bug, the tab title gone suddenly after activate the screen from sleep screen.

**Comment by ogaclejapan** [comment]
Hi, @encryptgo 
Do you really a problem of this library?
I think that it is not in the tab library problem.

Please show me all the code in the `onCreate(...)`
I want to look at the code until `SmartTabLayout#setViewPager(...)` is set.

**Comment by encryptgo** [comment]
Hi @ogaclejapan, yes i really sure because it occur on lollipop only.

**Comment by ogaclejapan** [comment]
I will not be able to raise this issue in my environment.
I think the view is all gone by the destruction of Activity.
So, we will close the issue.
