### ISSUE TITLE
SetTypeface on tab text

### ISSUE THREAD

**Issue by amirghm** [ogaclejapan/SmartTabLayout#61]
Hi

Please add settypface method to tab textview

thanks

**Comment by ogaclejapan** [comment]
Hi, @amirghm 
Try using the layout of the custom tab :+1: 
https://github.com/ogaclejapan/SmartTabLayout/issues/5

**Comment by ogaclejapan** [comment]
For a long time, there is no response.
So, we will close the issue.

**Comment by amirghm** [comment]
hisorry i am new to

**Comment by amirghm** [comment]
sorry I am new to issue writing, I set custom layout and solve my problem, thank you for amazing library and sorry for late response

**Comment by amirghm** [comment]
sorry I am new to issue writing, I set custom layout and solve my problem,
thank you for amazing library and sorry for late response
