### ISSUE TITLE
how to set indicator_trick1 to be center?

### ISSUE THREAD

**Issue by AhmadVatani** [ogaclejapan/SmartTabLayout#63]
I created 3 tab and now I want to show this tab in center of layout or make it full width.
what should i do?

**Comment by ogaclejapan** [comment]
Hi, @AhmadVatani 

Is this image?

![Image](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsTWtHNEdHQjEyVzg/components_tabs_usage_specs4.png)

**Comment by AhmadVatani** [comment]
YES, but i put  android:layoutDirection="rtl"  attribute and make it center.
tnx

**Comment by tamtom** [comment]
this didn't work for me !
