### ISSUE TITLE
Using with custom ViewPager?

### ISSUE THREAD

**Issue by Rexota** [ogaclejapan/SmartTabLayout#66]
I have a custom view pager, how can I use it?

Because I'm getting error:

    viewPagerIndicator.setViewPager(customViewPager); //error

**Comment by ogaclejapan** [comment]
Hi, @Rexota 

Please show me a stack trace of the error.

**Comment by Rexota** [comment]
Android studio gives error because my.pac.CustomViewPager isn't same type with SmartTabLayout's ViewPager.
