### ISSUE TITLE
how can i use my own Adapter

### ISSUE THREAD

**Issue by xiejinpeng007** [ogaclejapan/SmartTabLayout#72]
Hi ,thanks for the awesome widget,but i have some questions: when I use SmartTabLayout ,I don't want to use the FragmentItemAdapter/ViewPagerItemAdapter in utility, I want to use my own ViewPagerAdapter. But, I don't know how to do it. Is there anyway to do it? thanks for help.

**Comment by ogaclejapan** [comment]
HI, @xiejinpeng007 

You only need to set the ViewPager. :+1: 

```
ViewPager pager = ... ;
ViewPagerAdapter = (set the your view pager adapter) ;
pager.setAdapter(viewPagerAdapter);

SmartTabLayout tabLayout = ... ;
tabLayout.setViewPager(pager);

```

**Comment by ghost** [comment]
@ogaclejapan how to set the title?
