### ISSUE TITLE
change color of the tab text programmatically in Java code

### ISSUE THREAD

**Issue by Fakher-Hakim** [ogaclejapan/SmartTabLayout#75]

**Comment by ogaclejapan** [comment]
Hi, @Fakher-Hakim 

Please use this method.

```
View tabView = tabLayout.getTabAt(position);
```

Solved?

**Comment by Fakher-Hakim** [comment]
Ok i get the position of the tab but i can't find any method to change the text color !
i just get these 2 methods: 
setTextAlignment()
setTextDirection()

**Comment by ogaclejapan** [comment]
HI, @Fakher-Hakim 

If you are using the default tab you need to transform yourself.

```
TextView tabView = (TextView) tabLayout.getTabAt(position);
```

If you specify a custom tab layout, please use the findViewById.

```xml

<com.ogaclejapan.smarttablayout.SmartTabLayout
    ....
    app:stl_customTabTextLayoutId="@layout/custom_tab"
    app:stl_customTabTextViewId="@id/custom_text"
    ....
    />

```

```
TextView tabView = (TextView) tabLayout.getTabAt(position).findViewById(R.id.custom_text);
```

**Comment by ogaclejapan** [comment]
For a long time, there is no response.
So, we will close the issue.
