### ISSUE TITLE
Issue using custom_tab_icon with my code

### ISSUE THREAD

**Issue by a-random-package** [ogaclejapan/SmartTabLayout#79]
Okay, so, it's not MY code. Long story short, the developer I was working with up and decided if I wanted any further updates or help I would have to pay. (He was kind enough to direct me to this library though)

I can get everything working until the custom java comes in. I'm not a developer, more front-end but I'm a designer first and foremost. I dug through all issues and found one that looked hopeful for me here: https://github.com/ogaclejapan/SmartTabLayout/issues/34

Here is how I tried to implement it:

    package com.arandompackage.banded.fragment;

    import android.app.SearchManager;
    import android.content.Context;
    import android.content.res.Resources;
    import android.graphics.Color;
    import android.os.Bundle;
    import android.support.v4.app.Fragment;
    import android.support.v4.view.PagerAdapter;
    import android.support.v4.view.ViewPager;
    import android.support.v7.widget.SearchView;
    import android.util.Log;
    import android.view.LayoutInflater;
    import android.view.Menu;
    import android.view.MenuInflater;
    import android.view.MenuItem;
    import android.view.View;
    import android.view.ViewGroup;
    import android.view.inputmethod.InputMethodManager;
    import android.widget.ImageView;
    import android.widget.ProgressBar;

    import com.google.analytics.tracking.android.Fields;
    import com.google.analytics.tracking.android.MapBuilder;

    import com.arandompackage.banded.R;
    import com.arandompackage.banded.ThemeApp;
    import com.arandompackage.banded.fragment.adapters.IconsFragmentAdapter;
    import com.arandompackage.banded.fragment.icons.IconBoolean;

    import com.arandompackage.banded.util.ApplyTheme;
    import com.ogaclejapan.smarttablayout.SmartTabLayout;

    public class IconsFrag extends Fragment {

    public static final String FRAG_TAG = "icons";

    private ViewPager mViewPager;

    private IconsFragmentAdapter mSectionsPagerAdapter;
    private ProgressBar progressBar;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        Log.i(FRAG_TAG, "onCreate");
        super.onCreate(savedInstanceState);

        setHasOptionsMenu(true);
        setRetainInstance(true);
    }

    final LayoutInflater inflater = LayoutInflater.from(this);
    final Resources res = getResources();

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState){
        Log.i(FRAG_TAG, "onCreateView");
        View view = inflater.inflate(R.layout.custom_tab_icon, container, false);
        ImageView icon = (ImageView) View.findViewById(R.id.custom_tab_icon);
        switch (position) {
            case 0:
                icon.setImageDrawable(res.getDrawable(R.drawable.ic_exit_to_app_24dp));
                break;
            case 1:
                icon.setImageDrawable(res.getDrawable(R.drawable.ic_crop_original_24dp));
                break;
            case 2:
                icon.setImageDrawable(res.getDrawable(R.drawable.ic_exit_to_app_24dp));
                break;
            case 3:
                icon.setImageDrawable(res.getDrawable(R.drawable.ic_exit_to_app_24dp));
                break;
            case 4:
                icon.setImageDrawable(res.getDrawable(R.drawable.ic_exit_to_app_24dp));
                break;
            case 5:
                icon.setImageDrawable(res.getDrawable(R.drawable.ic_exit_to_app_24dp));
                break;
            default:
                throw new IllegalStateException("Invalid position: " + position);
        }

        if (view != null) {
            Log.i(FRAG_TAG, "view != null");
            mViewPager = (ViewPager) view.findViewById(R.id.viewpager);

            mViewPager.setAdapter(new IconsFragmentAdapter(getChildFragmentManager(), getActivity()));

            SmartTabLayout viewPagerTab = (SmartTabLayout) view.findViewById(R.id.viewpagertab);
            viewPagerTab.setViewPager(mViewPager);

            progressBar = (ProgressBar) getActivity().findViewById(R.id.base_progressSpinner);
            progressBar.setVisibility(View.VISIBLE);
        }
        return view;
    }

    @Override
    public void onStart() {
        Log.i(FRAG_TAG, "onStart");
        super.onStart();
        ThemeApp.getGaTracker().send(MapBuilder.createAppView().set(Fields.SCREEN_NAME, FRAG_TAG).build());
    }

    @Override
    public void onResume() {
        Log.i(FRAG_TAG, "onResume");
        super.onResume();

        if (IconBoolean.getValue()){
            mViewPager.setAdapter(new IconsFragmentAdapter(getChildFragmentManager(), getActivity()));

            IconBoolean.setValue(false);
        }
    }

    @Override
    public void onPrepareOptionsMenu (Menu menu) {
        Log.i(FRAG_TAG, "onPrepareOptionsMenu");
        MenuInflater inflater = getActivity().getMenuInflater();
        inflater.inflate(R.menu.icon_menu, menu);
        MenuItem searchItem = menu.findItem(R.id.search);

        SearchManager searchManager = (SearchManager) getActivity().getSystemService(Context.SEARCH_SERVICE);

        SearchView searchView = (SearchView) searchItem.getActionView();
        SearchView.SearchAutoComplete autoCompleteTextView = (SearchView.SearchAutoComplete) searchView.findViewById(R.id.search_src_text);

        if (autoCompleteTextView != null) {
            int theme = ApplyTheme.getTheme(getActivity());
            if (theme == 0) {
                autoCompleteTextView.setDropDownBackgroundDrawable(getResources().getDrawable(R.drawable.app_menu_dropdown_panel_holo_light));
            } else {
                autoCompleteTextView.setDropDownBackgroundDrawable(getResources().getDrawable(R.drawable.app_menu_dropdown_panel_holo_dark));
            }
        }
        searchView.setSearchableInfo(searchManager.getSearchableInfo(getActivity().getComponentName()));

    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        Log.i(FRAG_TAG, "onOptionsItemSelected");
        return super.onOptionsItemSelected(item);
    }

    @Override
    public void onPause() {
        super.onPause();
        getActivity().invalidateOptionsMenu();
        // hide the keyboard in order to avoid getTextBeforeCursor on inactive InputConnection
        InputMethodManager inputMethodManager = (InputMethodManager)getActivity().getSystemService(Context.INPUT_METHOD_SERVICE);
        inputMethodManager.hideSoftInputFromWindow(getView().getWindowToken(), 0);
    }
}
Here is my custom tab xml:

    <?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <com.ogaclejapan.smarttablayout.demo.TintableImageView
        android:id="@+id/custom_tab_icon"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:scaleType="center"
        app:tint="@color/white"
        />

</LinearLayout>

I've also added the TintableImageView.java

I'm getting errors with the 
    ImageView icon = (ImageView) View.findViewById(R.id.custom_tab_icon);

It says: non-static variable this cannot be referenced from a static context and also that 'position' cannot be resolved...

I've gone to SO and looked over the dozens of questions regarding the errors and the best one is this one: http://stackoverflow.com/questions/2559527/non-static-variable-cannot-be-referenced-from-a-static-context?lq=1

But like I said, Im a designer and I can't interpret all of this to get it working. Any help would be very appreciated.

**Comment by nimble** [comment]
I know this is going to sound really trivial but try changing the line: 
View.findViewById(R.id.custom_tab_icon);
to lowercase view as in 
view.findViewById(R.id.custom_tab_icon);
You have defined a variable, View view;, where view is the variable of type View. You need to use the variable, view, not its type which is, View.

**Comment by a-random-package** [comment]
Oh! Ok, I get that now. Thank you! I ended up changing 

    final LayoutInflater inflater = LayoutInflater.from(this);

to

    final LayoutInflater inflater = LayoutInflater.from(getContext());

and that cleared the error on "this"

But the switch is still throwing the error:

Error:(81, 72) error: cannot find symbol variable position

I'm pretty sure that's because of where I have placed the code, but I'm not 100% where else it could go.

**Comment by ogaclejapan** [comment]
I am sorry for the late answer.

I think this library is not the cause.
Because, I will close.
