### ISSUE TITLE
Multiple dex files define Lcom/ogaclejapan/smarttablayout/utils/BuildConfig

### ISSUE THREAD

**Issue by T0bbes** [ogaclejapan/SmartTabLayout#80]
Hi,

i'm using the gradle tool 1.4.0 and when i'm trying to use your library i'm getting the following error message:

```
:app:transformClassesAndResourcesWithExtractJarsForDebug UP-TO-DATE

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/ogaclejapan/smarttablayout/utils/BuildConfig;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)


:app:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.transform.api.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

Does anybody know how to solve this?

**Comment by ogaclejapan** [comment]
Hi, @T0bbes 

Do you define both the `utils-v4` and `utils-v13`?

**Comment by ogaclejapan** [comment]
http://stackoverflow.com/questions/25103288/multiple-dex-files-define-my-package-buildconfig-cant-find-the-cause

**Comment by ogaclejapan** [comment]
Please be either only one definition this util-xx library.
It is the same package name.

Solved ?

**Comment by T0bbes** [comment]
Sorry for my late answer.
I thought that i had defined just one util library but u are right - now i works.
Thanks!

**Comment by soheilghanbari1371** [comment]
sorry im new to android and i got this problem too
whta should i do exactly?

**Comment by ThePhoenix01** [comment]
When you add dependencies to build.gradle, use only **one** of the below
    compile 'com.ogaclejapan.smarttablayout:utils-v4:1.6.1@aar'
or
    compile 'com.ogaclejapan.smarttablayout:utils-v13:1.6.1@aar'

While utils-v4 contains the PagerAdapter implementation class for android.support.v4.app.Fragment,
utils-v13 library contains the PagerAdapter implementation class for android.app.Fragment. I prefer utils-v4.
