### ISSUE TITLE
Unable to change indicator color

### ISSUE THREAD

**Issue by susheel17** [ogaclejapan/SmartTabLayout#81]
How can I change the default indicator color in distribute evenly type layout?
app:stl_indicatorColor="#40C4FF"  I am using this attribute and changing the value but the color of the indicator does not change from default

**Comment by ogaclejapan** [comment]
HI, @susheel17 
I am sorry for the late answer.
Already solved?

I also do not know why not change.
Could you check again with my demo app?

layout/demo_basic.xml
```xml
<com.ogaclejapan.smarttablayout.SmartTabLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@id/viewpagertab"
    android:layout_width="match_parent"
    android:layout_height="@dimen/tab_height"
    app:stl_defaultTabTextColor="@color/white"
    app:stl_defaultTabTextHorizontalPadding="24dp"
    app:stl_indicatorColor="#40C4FF"
    app:stl_indicatorInterpolation="linear"
    app:stl_indicatorThickness="3dp"
    app:stl_underlineThickness="1dp"
    />

```

I worked.

**Comment by susheel17** [comment]
@ogaclejapan : It's working now! Thanks :)
