### ISSUE TITLE
Animate tabs

### ISSUE THREAD

**Issue by denebchorny** [ogaclejapan/SmartTabLayout#86]
Now I'm back for an advice. I want to animate the tabs the first time the app is executed to let the user know that he has many options, more than he can see.

This is an example: https://imgflip.com/gif/tb9hb

I want to do this programatically (I thought to emulate swipe but I think it's not the right way to do it). I want to displace the tabs left to right just once. It will be an optical indicator for the user.

how can I do it?

Thanks in advance.

**Comment by ogaclejapan** [comment]
Hi, @denebchorny 
I am sorry for the late answer.
Already solved?

SmartTabLayout inherits the HorizontalScrollView.
So, I think that it should I call the `scrollTo(xxx)` with the animation.
