### ISSUE TITLE
How to start from left, end in right, when I user always in center

### ISSUE THREAD

**Issue by imcloud** [ogaclejapan/SmartTabLayout#89]
sorry, PE teacher taught my English,so  not good

always in center  is  very cool

but    the  first tab also in center ,.
I wish first tab in left, keep in center just while you slide to center

like https://github.com/nshmura/RecyclerTabLayout

I love SmartTabLayout , I want same effect on it

**Comment by ogaclejapan** [comment]
Hi, @imcloud 

It was just implemented : )

```
stl_titleOffset="auto_center"
```

I will release 1.5.0 in 2, 3 days .

**Comment by ogaclejapan** [comment]
Right now, 1.5.0 released : )
So, this issue it will close.
