### ISSUE TITLE
Don't understand how to attach fragment to activity

### ISSUE THREAD

**Issue by MrDarpan** [ogaclejapan/SmartTabLayout#9]
I am using this in my activity but activity only shows the tabs but no fragment content...

**Activity Class:**
```java
public class ActivityUserProfile extends ActionBarActivity{

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_user_profile);

        FragmentPagerItemAdapter adapter = new FragmentPagerItemAdapter(
                getSupportFragmentManager(), FragmentPagerItems.with(ActivityUserProfile.this)
                .add(R.string.title_basic, FragmentProfileBasic.class)
                .create());

        ViewPager viewPager = (ViewPager) findViewById(R.id.viewpager);
        viewPager.setAdapter(adapter);

        SmartTabLayout viewPagerTab = (SmartTabLayout) findViewById(R.id.viewpagertab);
        viewPagerTab.setViewPager(viewPager);
    }
}
```

**Fragment Class:**
```java
public class FragmentProfileBasic extends Fragment {

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.fragment_profile_basic, container, false);
        return rootView;
    }
}
```

**Comment by ogaclejapan** [comment]
Hi, @MrDarpan 

This code I think no problem.
Can I view the layout file here?　
R.layout.activity_user_profile

Fragment is using the support version?

**Comment by MrDarpan** [comment]
*** activity_user_profile***
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:font="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <LinearLayout
                android:id="@+id/content"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="horizontal"
                android:weightSum="10"
                android:padding="@dimen/fragment_default_padding"
                android:background="@color/color_light_gray"
                android:visibility="visible">

                <ImageView
                    android:id="@+id/profilePicture"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_weight="3"
                    android:minWidth="100dp"
                    android:minHeight="100dp"
                    android:background="@color/color_dark_gray"
                    android:padding="2dp"
                    android:scaleType="fitXY" />

                <LinearLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:paddingLeft="@dimen/fragment_default_padding"
                    android:paddingRight="@dimen/fragment_default_padding"
                    android:orientation="vertical"
                    android:layout_weight="7">

                    <net.kianoni.fontloader.TextView
                        android:id="@+id/userName"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:text="User Name"
                        android:textSize="18sp"
                        font:fontFile="fonts/Raleway-Bold.ttf" />

                    <net.kianoni.fontloader.TextView
                        android:id="@+id/userEmail"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:text="Profile: 10% Completed"
                        android:textSize="16sp"
                        font:fontFile="fonts/Raleway-Regular.ttf" />

                </LinearLayout>

            </LinearLayout>

            <com.ogaclejapan.smarttablayout.SmartTabLayout
                android:id="@+id/viewpagertab"
                android:layout_width="match_parent"
                android:layout_height="48dp"
                app:stl_indicatorAlwaysInCenter="false"
                app:stl_indicatorInFront="true"
                app:stl_indicatorInterpolation="smart"
                app:stl_indicatorColor="@color/color_dark_orange"
                app:stl_indicatorThickness="4dp"
                app:stl_indicatorCornerRadius="0dp"
                app:stl_underlineColor="@color/color_dark_orange"
                app:stl_underlineThickness="1dp"
                app:stl_dividerColor="@color/color_dark_orange"
                app:stl_dividerThickness="1dp"
                app:stl_defaultTabTextAllCaps="true"
                app:stl_defaultTabTextColor="#FC000000"
                app:stl_defaultTabTextSize="12sp"
                app:stl_defaultTabTextHorizontalPadding="16dp"
                app:stl_defaultTabTextMinWidth="0dp"
                app:stl_distributeEvenly="true"/>

            <android.support.v4.view.ViewPager
                android:id="@+id/viewpager"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_below="@id/viewpagertab" />

        </LinearLayout>

    </ScrollView>

</LinearLayout>
```

**Comment by ogaclejapan** [comment]
Hi, @MrDarpan 
Do works!  
Add `android:fillViewport="true"`

```xml

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fillViewport="true">

        ...

    </ScrollView>

```

The problem is not associated with this library... :o

**Comment by NhenDen** [comment]
Hi ogaclejapan.
I add Scrollview with smart tab layout but Scrollview not working :(
Help me.
Code of me:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/colorWhite"
    android:gravity="center"
    android:orientation="vertical">

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginBottom="@dimen/PADDING_APP"
        android:layout_marginLeft="@dimen/PADDING_APP"
        android:layout_marginRight="@dimen/PADDING_APP"
        android:layout_marginTop="@dimen/PADDING_APP"
        android:fillViewport="true"
        android:scrollbars="none">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <LinearLayout
                android:id="@+id/fragment_login_imgCover"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical">

                <ImageView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="@drawable/logo" />

                <View
                    android:layout_width="match_parent"
                    android:layout_height="1dp"
                    android:layout_marginTop="-49dp"
                    android:alpha="0.3"
                    android:background="@color/colorWhite" />

            </LinearLayout>

            <com.ogaclejapan.smarttablayout.SmartTabLayout
                android:id="@+id/fragment_home_viewpagertab"
                android:layout_width="match_parent"
                android:layout_height="48dp"
                android:layout_marginTop="-48dp"
                android:background="@null"
                app:stl_clickable="true"
                app:stl_customTabTextLayoutId="@layout/tab_item_home"
                app:stl_customTabTextViewId="@+id/tab_item_home_textView"
                app:stl_defaultTabBackground="?attr/selectableItemBackground"
                app:stl_defaultTabTextAllCaps="false"
                app:stl_defaultTabTextColor="@color/colorTextDemo"
                app:stl_defaultTabTextHorizontalPadding="16dp"
                app:stl_defaultTabTextMinWidth="40dp"
                app:stl_defaultTabTextSize="12sp"
                app:stl_distributeEvenly="false"
                app:stl_dividerColor="@android:color/transparent"
                app:stl_dividerThickness="1dp"
                app:stl_drawDecorationAfterTab="true"
                app:stl_indicatorColor="@color/colorHighlight"
                app:stl_indicatorCornerRadius="2dp"
                app:stl_indicatorGravity="bottom"
                app:stl_indicatorInFront="false"
                app:stl_indicatorInterpolation="smart"
                app:stl_indicatorThickness="3dp"
                app:stl_indicatorWithoutPadding="false"
                app:stl_overlineColor="@android:color/transparent"
                app:stl_overlineThickness="0dp"
                app:stl_titleOffset="auto_center"
                app:stl_underlineColor="@android:color/transparent"
                app:stl_underlineThickness="1dp" />

            <android.support.v4.view.ViewPager
                android:id="@+id/fragment_home_viewpager"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

        </LinearLayout>

    </ScrollView>

</LinearLayout>

**Comment by pchauhan** [comment]
I am facing same issue @NhenDen Did you got any soluction?
