### ISSUE TITLE
Horizontal swipe with RTL native works in the wrong direction

### ISSUE THREAD

**Issue by dayerdl** [ogaclejapan/SmartTabLayout#91]
If I change the app to a RTL language and enable RTL support on the manifest, the tabs are in the correct order(from right to left) but when I try to swipe to the left the screen does not allow you. So basically the swipe is not RTL but still LTF.

**Comment by ogaclejapan** [comment]
Hi, @dayerdl 
Thank you for reporting.

ViewPager does not change even if set the RTL
https://code.google.com/p/android/issues/detail?id=56831
