### ISSUE TITLE
stl_underlineColor attribute overlaps indicator

### ISSUE THREAD

**Issue by VictorAlbertos** [ogaclejapan/SmartTabLayout#93]
Hi, when I don't specify a color for the stl_underlineColor attribute the indicator looks fine:

<img width="415" alt="screen shot 2015-11-06 at 11 12 05" src="https://cloud.githubusercontent.com/assets/2614726/10994570/9394dde4-8477-11e5-8c12-338972189673.png">

But when I specify a color for the stl_underlineColor attribute the indicator is overlapped. 

<img width="419" alt="screen shot 2015-11-06 at 11 12 50" src="https://cloud.githubusercontent.com/assets/2614726/10994587/a363b2e0-8477-11e5-8edc-b3a49286d49c.png">

A workaround it is increase the value dp for  the attribute stl_indicatorThickness

<img width="430" alt="screen shot 2015-11-06 at 11 13 32" src="https://cloud.githubusercontent.com/assets/2614726/10994604/bcc62830-8477-11e5-84cf-eb7bfb4602dc.png">

But, is this the expected behaviour?

**Comment by ogaclejapan** [comment]
Hi, @VictorAlbertos 

Please use `stl_indicatorInFront="true"`
By default, the underline is the front

**Comment by VictorAlbertos** [comment]
Thanks!
